### ISSUE TITLE
v0.2.15 build failure without any useful output

### ISSUE THREAD

**Issue by eternal-sorrow** [emersion/hydroxide#105]
I'm packaging hydroxide for gentoo in my overlay. The previous versions compiled well for me, but the last one fails compile and I don't see in the build log, why it happens. I'm unfamiliar with Go build system so I don't know where to look to get it working. [Here](https://0x0.st/iys3.txt)'s my build log from portage, maybe someone can help me with getting it right.

**Comment by emersion** [comment]
This is a bug with your distribution. hydroxide uses Go modules and it doesn't seem like your build system uses them.

There are various error messages in the log:

```
# github.com/emersion/hydroxide/protonmail
src/github.com/emersion/hydroxide/protonmail/contacts.go:167:66: too many arguments in call to openpgp.CheckArmoredDetachedSignature
	have (openpgp.KeyRing, *bytes.Buffer, io.Reader, nil)
	want (openpgp.KeyRing, io.Reader, io.Reader)
src/github.com/emersion/hydroxide/protonmail/contacts.go:193:55: too many arguments in call to openpgp.CheckArmoredDetachedSignature
	have (openpgp.KeyRing, *strings.Reader, *strings.Reader, nil)
	want (openpgp.KeyRing, io.Reader, io.Reader)
src/github.com/emersion/hydroxide/protonmail/crypto.go:39:21: subkey.PublicKey.KeyExpired undefined (type *packet.PublicKey has no field or method KeyExpired)
src/github.com/emersion/hydroxide/protonmail/crypto.go:56:137: i.SelfSignature.SigExpired undefined (type *packet.Signature has no field or method SigExpired)
src/github.com/emersion/hydroxide/protonmail/crypto.go:73:21: subkey.PublicKey.KeyExpired undefined (type *packet.PublicKey has no field or method KeyExpired)
src/github.com/emersion/hydroxide/protonmail/crypto.go:87:80: i.SelfSignature.SigExpired undefined (type *packet.Signature has no field or method SigExpired)
src/github.com/emersion/hydroxide/protonmail/srp.go:45:41: too many arguments in call to openpgp.CheckDetachedSignature
	have (openpgp.EntityList, *bytes.Reader, io.Reader, nil)
	want (openpgp.KeyRing, io.Reader, io.Reader)
```

**Comment by eternal-sorrow** [comment]
>This is a bug with your distribution.

It's not a bug. Portage compile phase is sandboxed so it can't download the remote modules. That's why modules are downloaded by Portage before the compilation starts.

>There are various error messages in the log:

Thanks for pointing it out. I'll see what module versions are wrong in my ebuild.

**Comment by eternal-sorrow** [comment]
I just didn't notice that `golang.org/x/crypto` was replaced with `github.com/ProtonMail/crypto`

**Comment by emersion** [comment]
I'd suggest using [`go mod vendor`](https://golang.org/ref/mod#tmp_32) instead.

**Comment by eternal-sorrow** [comment]
>I'd suggest using go mod vendor instead.

This may be reasonable for live ebuilds that build directly from git master. But the ebuild that downloads sources as a tarball and than vendors modules directly from VCS is just.. wrong. Also it will never be accepted in the main portage tree (it's not my goal though).
