### ISSUE TITLE
Where is auth file saved? (for docker persistence)

### ISSUE THREAD

**Issue by frogger72** [emersion/hydroxide#109]
I can't seem to find where the auth file is saved. I just see an empty app folder in the home directory. I'm running as a docker, so I'm trying to figure out what file or directory to persist - currently each container restart requires a re-auth.

**Comment by harleylang** [comment]
I'm currently working on a Dockerfile and docker-compose.yml that will reauth on each container restart. I am not sure if it will be a separate repo or pulled in here, but either way I'll report back in a few days.

**Comment by emersion** [comment]
It's saved in `~/.config/hydroxide/auth.json`.

**Comment by harleylang** [comment]
Regarding Docker configurations, @frogger72 see: https://github.com/harleylang/hydroxide-docker

**Comment by frogger72** [comment]
Thanks @emerson and @harleylang. Base functionality is working now. I have a similar setup though I am setting all interfaces to 0.0.0.0 with flags in the docker command.

I think the biggest value-add from a docker-compose perspective will be to add a TLS wrapper service, ideally using https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion to also automate the cert requests

Here's a sample nginx configuration that might work: https://github.com/jc21/nginx-proxy-manager/issues/450

**Comment by harleylang** [comment]
> Thanks @Emerson and @harleylang. Base functionality is working now. I have a similar setup though I am setting all interfaces to 0.0.0.0 with flags in the docker command.

Yes, I lost 1-2 hours before coming to this realization while preparing the docker repo in my previous post! Hopefully this helps someone else avoid that issue in the future. 

> I think the biggest value-add from a docker-compose perspective will be to add a TLS wrapper service, ideally using https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion to also automate the cert requests
> 
> Here's a sample nginx configuration that might work: [jc21/nginx-proxy-manager#450](https://github.com/jc21/nginx-proxy-manager/issues/450)

This is a little bit out of my wheelhouse nonetheless I'm willing to learn.

If you want to drop a pull request in the other repo, I'm happy to explore an improved security setup. Plaintext storage won't cut it so this is a natural next step.
