### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by QuentinI** [emersion/hydroxide#110]
Since ProtonMail is [blocked in Russia](https://protonmail.com/blog/russia-block-2020/), I can't get hydroxide to work with direct Internet access.
For various reasons I'm not using a VPN and rely on SOCKS5 proxy, which hydroxide doesn't support natively, as far as I am aware. Only solution that doesn't involve tinkering with virtual network interfaces (which I'm not a big fan of) that I'm aware of is proxychains, but it doesn't seem to work with hydroxide:
```
$ proxychains4 hydroxide -debug auth username
[proxychains] config file found: /home/username/.proxychains/proxychains.conf
[proxychains] preloading [...]/lib/libproxychains4.so
[proxychains] DLL init
Password: 
2020/07/23 19:03:31 >> POST /api/auth/info
2020/07/23 19:03:31 {"Username":"username"}
2020/07/23 19:03:31 Post "https://mail.protonmail.com/api/auth/info": dial tcp 224.0.0.1:443: connect: network is unreachable
```
So the question is, are you willing to implement/accept PR implementing proxy support?

**Comment by QuentinI** [comment]
Never mind, I wasn't aware that Go's `http.DefaultClient` - and by extension hydroxide - respects `HTTPS_PROXY` environment variable and friends; and _of course_ I found out about it three minutes after I opened this issue.

**Comment by PRESFIL** [comment]
Specifing protocol handler helped me:

`HTTPS_PROXY='socks5://127.0.0.1:9050' hydroxide ...`

**Comment by bruceleerabbit** [comment]
@PRESFIL If that really worked, I must say that’s a bizarre departure from conventions. Here’s what’s normal: all browsers that use any of the following variables use them for ***HTTP*** proxies, not ***SOCKS***:
* `http_proxy`
* `https_proxy`
* `HTTP_PROXY`
* `HTTPS_PROXY`

A typical port used for this purpose is 8118, thus if you run `privoxy` you would have a var like:

`http_proxy=http://127.0.0.1:8118/`

Some browsers also support SOCKS proxies, but not by way of the above vars. Instead you have something like:
```
curl --socks4a 127.0.0.1:9050
curl --socks5h 127.0.0.1:9050
curl -x 'socks5h://127.0.0.1:9050'
wire-desktop --proxy-server='socks5://127.0.0.1:9050'
chromium --proxy-server='socks5://127.0.0.1:9050' --host-resolver-rules='MAP * ~NOTFOUND , EXCLUDE 127.0.0.1'
SOCKS_SERVER=127.0.0.1:9050 TORSOCKS_CONF_FILE=/etc/tsocks.conf LD_PRELOAD=/usr/local/lib/torsocks_mods/libtorsocks.so epiphany
```

If Hydroxide really expects a SOCKS proxy to be mislabeled as an HTTP proxy, that’s a bug and @emersion should reopen this.
