### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by SmileEdge** [emersion/hydroxide#116]
Special characters are not encoded correctly.

With hydroxide through thunderbird:
![bug](https://user-images.githubusercontent.com/28065660/90552966-ecf2d200-e193-11ea-8593-18eba411fa20.png)

With protonmail webapp:
![ok](https://user-images.githubusercontent.com/28065660/90552958-eb290e80-e193-11ea-9474-aa8775e1a470.png)

**Comment by emersion** [comment]
Would be useful to have the (redacted) message headers to understand what's going on.

**Comment by SmileEdge** [comment]
For now, I can't provide any message redacted headers. There is the headers I received in case this may help. By the way, the subject of the message ("Votre colis vous attend dans votre boîte aux lettres") is correctly displayed by thunderbird, and it's the case for all mails with special characters like these.
```
Content-Type: multipart/mixed; boundary
 =12d9ae6d446d2d80af1555c410b95b781a43a03a24e64d3559ae5b99c686
Message-Id: 41210238995004@dmc.sfr-sh.fr
To: <couderc.arnaud@protonmail.com>
From: =?utf-8?q?Colis_Priv=C3=A9?= <livraison@colisprive.com>
Subject: =?utf-8?q?Votre_colis_vous_attend_dans_votre_bo
 =C3=AEte_aux_lettres?=
Date: Fri, 07 Aug 2020 16:31:00 +0200

--12d9ae6d446d2d80af1555c410b95b781a43a03a24e64d3559ae5b99c686
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

=EF=BB=BF<!DOCTYPE HTML PUBLIC =C2=AB -//W3C//DTD XHTML 1.0 Transitional //=
EN " =C2=AB http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd " >
```

**Comment by emersion** [comment]
Ah, we probably don't properly forward the `Content-Type` charset param.

**Comment by SmileEdge** [comment]
I'm sure it's something like that

**Comment by arvchristos** [comment]
This is an issue with Greek characters too

**Comment by garret** [comment]
I confirm there is an issue with Danish characters as well

**Comment by o-schneider** [comment]
I have the issue too, french content as the OP.

**Comment by emersion** [comment]
Does it help to change this line

https://github.com/emersion/hydroxide/blob/5dc0d0b2e860d726bc163f12d671733ab9c44825/imap/message.go#L177

to

```go
h.SetContentType(msg.MIMEType, map[string]string{"charset", "utf-8"})
```

**Comment by garret** [comment]
@emersion I would like to help but I am not very expert. I installed hydroxide (0.2.15) through the void linux package system. Do you know where I could find the file you mention to be modified?

**Comment by mrvik** [comment]
> Does it help to change this line
> 
> https://github.com/emersion/hydroxide/blob/5dc0d0b2e860d726bc163f12d671733ab9c44825/imap/message.go#L177
> 
> to
> 
> ```go
> h.SetContentType(msg.MIMEType, map[string]string{"charset": "utf-8"})
> ```

Will try now. Anyway it should work, Kmail it tries to open as ISO8859-1, but when you change encoding from "Auto" to "UTF8" it works well, so setting the header seems a logic change here.

**Comment by mrvik** [comment]
Works like a charm, all special characters are now properly handled

**Comment by emersion** [comment]
OK, cool. If you submit a PR I'll merge it.
