### ISSUE TITLE
Email content empty -- [2000] The IDs is required

### ISSUE THREAD

**Issue by skewty** [emersion/hydroxide#117]
Partial log:
```
2020/09/13 07:03:33 Synchronizing mailbox All Mail...
2020/09/13 07:03:51 Synchronizing mailbox All Mail: done.
2020/09/13 07:04:09 Synchronizing mailbox INBOX...
2020/09/13 07:04:21 Synchronizing mailbox INBOX: done.
2020/09/13 07:04:47 request failed: PUT https://mail.protonmail.com/api/messages/delete: [2000] The IDs is required
2020/09/13 07:04:47 Synchronizing mailbox Archive...
2020/09/13 07:04:48 Synchronizing mailbox Archive: done.
2020/09/13 07:04:50 request failed: PUT https://mail.protonmail.com/api/messages/delete: [2000] The IDs is required
2020/09/13 07:04:50 Synchronizing mailbox Drafts...
2020/09/13 07:04:50 Synchronizing mailbox Drafts: done.
2020/09/13 07:04:52 request failed: PUT https://mail.protonmail.com/api/messages/delete: [2000] The IDs is required
2020/09/13 07:04:53 Synchronizing mailbox Sent...
2020/09/13 07:04:55 Synchronizing mailbox Sent: done.
2020/09/13 07:04:55 request failed: PUT https://mail.protonmail.com/api/messages/delete: [2000] The IDs is required
2020/09/13 07:04:55 Synchronizing mailbox Spam...
2020/09/13 07:04:55 Synchronizing mailbox Spam: done.
2020/09/13 07:04:56 request failed: PUT https://mail.protonmail.com/api/messages/delete: [2000] The IDs is required
2020/09/13 07:04:56 Synchronizing mailbox Starred...
2020/09/13 07:04:56 Synchronizing mailbox Starred: done.
2020/09/13 07:04:57 request failed: PUT https://mail.protonmail.com/api/messages/delete: [2000] The IDs is required
2020/09/13 07:04:57 Synchronizing mailbox Trash...
2020/09/13 07:05:01 Synchronizing mailbox Trash: done.
2020/09/13 07:05:01 request failed: PUT https://mail.protonmail.com/api/messages/delete: [2000] The IDs is required
2020/09/13 07:06:05 Received update event for message mpHwT9Poec5JOv7ug-I4-NPWgbyA4_--pOpN-I6psi1mNIFWqSzWJ_cobmBnuqHYs2lekM8_neKVyTm4Y_QFAQ==
2020/09/13 07:06:08 Received update event for message _36naMs4xkaRtb1qbRj8XjZRp9xhd6j9s_21ImpaP2PiRKm8z8-K_UFRqBsYp4HokSNgY9dmU49dSsQ8G6nv1A==
2020/09/13 07:06:08 request failed: PUT https://mail.protonmail.com/api/messages/delete: [2000] The IDs is required
2020/09/13 07:06:12 request failed: PUT https://mail.protonmail.com/api/messages/delete: [2000] The IDs is required
2020/09/13 07:06:14 request failed: PUT https://mail.protonmail.com/api/messages/delete: [2000] The IDs is required
2020/09/13 07:06:15 request failed: PUT https://mail.protonmail.com/api/messages/delete: [2000] The IDs is required
```

**Comment by emersion** [comment]
Would need to check what the request looks like when sending from the webmail, and then compare with what we do.

**Comment by skewty** [comment]
So I ran it again with `--debug` and noticed this:
```
2020/09/13 07:13:18 << GET /api/events/sT9swwabkP5GzdmQtgFDuL41B5eh3h1-nA6c_6JlVdFFZfwVmSM0da1dnHk7uILcmdhYGppTJOovxojSDaPDNg==
2020/09/13 07:13:18 &struct { protonmail.resp; *protonmail.Event }{resp:protonmail.resp{Code:1000, RawAPIError:(*protonmail.RawAPIError)(nil)}, Event:(*protonmail.Event)(0xc000111a00)}
```

Looks like the data being returned is different than expected.  Perhaps the API changed?

**Comment by skewty** [comment]
I installed GoLand to see if I could figure this out myself.

Here is what I got when I set a breakpoint on protonmail.go:172

![Screenshot from 2020-09-13 07-45-38](https://user-images.githubusercontent.com/9087223/93021057-7a5bf300-f595-11ea-970d-654f0ffb0ae1.png)

**Comment by skewty** [comment]
I tried adding the account to Evolution and I can now see email contents.  So I am guessing Geary does IMAP differently than Evolution.

The client I was using is [Geary](https://gitlab.gnome.org/GNOME/geary).  Geary doesn't load email contents.

I still get "The IDs is required" errors in Evolution but at least I can see email contents.
```
Error while Fetching summary information for new messages in “ProtonMail : Trash”.
Error expunging message: The IDs is required
```

**Comment by mrvik** [comment]
I think this IDs issue is too generic, I got it when tried to remove emails from inbox on KMail (deleting them from web client and refreshing local client works fine) and this error also appeared when trying to send an email with an embedded image (HTML email) but idk if this issue shares the same URL.

```
nov 25 16:11:20 nebuchadnezzar hydroxide[420]: 2020/11/25 16:11:20 request failed: PUT https://mail.protonmail.com/api/messages/delete: [2000] El IDs es obligatorio
```
This happens when I try to delete emails. Maybe it's an API issue.

**Comment by dslul** [comment]
I'm not sure if it's a geary issue or not, but the problem of invisible mails has nothing to do with the message in the title.

This is what appears on Geary debug log when trying to open any mail from hydroxide:

> Could not get message text. Could not find any "text/plain" parts

**Comment by mrvik** [comment]
I have been investigating this issue and the call on `imap/mailbox.go:560` has `apiIDs` slice empty

**Comment by emersion** [comment]
Right. We should probably avoid sending an API call if the slice is empty.

**Comment by mrvik** [comment]
Yes, that would be a "failfast". I'll try to investigate why is `mbox.deleted` (which is copied into this slice) empty.

**Comment by mrvik** [comment]
Ok, seems like the function updating `mbox.deleted` is `(*mailbox).UpdateMessagesFlags` but it is not always called before client sends an `EXPUNGE` command, so the handler for that command should go through mails and extract their ID if `\delete` flag is set.
I'll try to make a patch and test if it works.

Mail clients send `EXPUNGE` altrought they didn't mark any mails for deletion (just to do some involuntary GC) on the sync process, so:
* As you mentioned, we should check if there are IDs marked for deletion to avoid failing so hard (IDK if there is a method to politely say "there is no mail marked for deletion", maybe juan an OK?)
* And a loop over messages checking ID is needed (trying to write a patch now)

**Comment by mrvik** [comment]
Ok, I think it's done, but I'm watching packets and can't see my mail client flagging mails as anything (as it does with the `\Seen` flag). I think there's a bug on KIMAP (currently diving on their code) and the only patch needed here is to check if slice is empty.

**Comment by emersion** [comment]
Hm. And we properly advertise support for `\Deleted` here: https://github.com/emersion/hydroxide/blob/b4e52ac71555142e2d9db4c0f85ba71f6fc96c30/imap/mailbox.go#L64

Note that `EXPUNGE` permanently deletes messages. Maybe clients aren't configured to do this by default?

**Comment by mrvik** [comment]
> Hm. And we properly advertise support for `\Deleted` here:
> 
> https://github.com/emersion/hydroxide/blob/b4e52ac71555142e2d9db4c0f85ba71f6fc96c30/imap/mailbox.go#L64

Yes, that's what I initially thought, but it's property advertised (and packet captures confirm it).

> Note that `EXPUNGE` permanently deletes messages. Maybe clients aren't configured to do this by default?

I edited my prev comment, yes, it depends on the mail client being used. Kmail (which uses KIMAP) does an expunge after every select (option is marked by default). Thunderbird doesn't to it by default. But the point here seems `\deleted` flag isn't set so when `EXPUNGE` is sent, there are no mails marked for deletion (but the client was instructed to).

**Comment by mrvik** [comment]
Oh, found it!

`\DeletedFlag` was not advertised as permanent, so clients didn't send it

**Comment by mrvik** [comment]
Now it's working. I'm making a PR

**Comment by emersion** [comment]
Fixed in https://github.com/emersion/hydroxide/commit/4903cb08dd8edc231a3db5e11f35ff2121260228
