### ISSUE TITLE
TLS & STARTTLS support

### ISSUE THREAD

**Issue by emersion** [emersion/hydroxide#13]
This will allow hydroxide to be hosted on a server and accessed from multiple remote clients.

**Comment by jeroen7s** [comment]
wouldn't this completely kill the privacy and security benefits from using a service like Protonmail?

**Comment by jvkdoodle** [comment]
I would like to have a bridge that I can access over a VPN connection. So I can use a different mail client on my iPhone and iPad rather than the protonmail app.  

So far I get SMTP to work but not IMAP. 

Neither with Hydroxide or the original bridge. 

I tried doing a reverse SSH tunnel mapping the port to the VPN server that way... for SMTP this works but IMAP does not.

**Comment by oap-bram** [comment]
+1 on this

**Comment by Trumpy** [comment]
Besides the TLS/StartTLS, I thought deploying it on a server to be remotely accessed was already a possibility.

**Comment by emersion** [comment]
Yes, this already works. But right now you'll need to setup a proxy to wrap connections with TLS if you want to access the server remotely.

**Comment by Trumpy** [comment]
Oh, thanks! This would be why I'm having issues connecting remotely.

**Comment by arichtman** [comment]
Re the reverse proxy offload of TLS - I think it can only be one that supports STARTTLS or has some kind of advanced features. I've been digging around trying to get Traefik to work and it seems only Nginx is capable of reverse proxy for IMAP and SMTP.

**Comment by emersion** [comment]
No, a plain TLS proxy should work as well. Just need to configure your email clients to use TLS instead of STARTTLS.

**Comment by tgunnoe** [comment]
How does one use such a plain TLS proxy? I'm looking to route a sourcehut smtp through hydroxide, but sourcehut expects a STARTTLS response.

**Comment by arichtman** [comment]
> 
> 
> How does one use such a plain TLS proxy? I'm looking to route a sourcehut smtp through hydroxide, but sourcehut expects a STARTTLS response. Running on the same server so nothing fancy.

If they're on the same server and you're confident it's secure then you don't need TLS. TLS on the same host is only to protect from other applications snooping on your messages. If it's not routing through the open web it's not exposed.

**Comment by tgunnoe** [comment]
`smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.`
It uses smtplib of python and part of the initial connection to the smtp mail server is `smtp.starttls()` https://git.sr.ht/~sircmpwn/core.sr.ht/tree/master/item/srht/email.py#L118

**Comment by arichtman** [comment]
Looks like you are going to need a reverse proxy running TCP TLS termination. This looks pretty on point https://docs.nginx.com/nginx/admin-guide/security-controls/terminating-ssl-tcp/

**Comment by tgunnoe** [comment]
Thanks! I'll check them out.
