### ISSUE TITLE
Support for the mutt-wizard script by Luke Smith

### ISSUE THREAD

**Issue by garret** [emersion/hydroxide#152]
I am quite noob with `mutt` and I have always been tempted to start using it. I found out the `mutt-wizard` script by Luke Smith which has an option to set up ProtonMail addresses when used together with the official ProtonMail bridge. 

Thus, after succeeding in using hydroxide with Thunderbird, I wanted to test it with mutt. However, it seems the script only accepts some sort of TLS with self-signed certificates (like the ProtonMail bridge does). 

Since the mutt-wizard script doesn't have support for that yet, are you aware of a workaround to use it together with hydroxide?

**Comment by paniash** [comment]
I would love to see support for mutt-wizard as well!

**Comment by emersion** [comment]
Can you open an issue on the mutt-wizard repo for hydroxide?

Regarding mutt configuration, I don't know. hydroxide's README has generic instructions. You can probably ask via a support IRC channel or mailing list how that translates to mutt.

**Comment by garret** [comment]
@emersion I had actually asked there and I was reverted here. I guess it is one of those things that nobody wants to take care and pinball the other. Unfortunately, I am not a coder so cannot provide any PR. I will revert to the official protonmail bridge. Thanks anyway.
