### ISSUE TITLE
How on Earth do I configure this for Kmail/Kontact???

### ISSUE THREAD

**Issue by NovaViper** [emersion/hydroxide#153]
Hi, I've been having issues getting this configured on KDE's Mail app (Kmail). I keep getting this error
```
imap/server: 2021/02/11 00:21:41 cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:58588: write: broken pipe
imap/server: 2021/02/11 00:21:41 cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:58588: write: broken pipe
imap/server: 2021/02/11 00:21:41 cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:58588: write: broken pipe
imap/server: 2021/02/11 00:21:41 cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:58588: write: broken pipe
imap/server: 2021/02/11 00:21:41 cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:58588: write: broken pipe
imap/server: 2021/02/11 00:21:42 cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:58590: write: connection reset by peer
imap/server: 2021/02/11 00:21:42 cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:58590: write: connection reset by peer
imap/server: 2021/02/11 00:21:42 cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:58590: write: connection reset by peer
imap/server: 2021/02/11 00:21:42 cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:58590: write: connection reset by peer
imap/server: 2021/02/11 00:21:42 cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:58590: write: connection reset by peer
imap/server: 2021/02/11 00:21:42 cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:58590: write: connection reset by peer
```
 Here are my settings for incoming:
![image](https://user-images.githubusercontent.com/7191115/107607651-704f2680-6bff-11eb-872e-bb53c7089319.png)
![image](https://user-images.githubusercontent.com/7191115/107607691-8826aa80-6bff-11eb-8ee4-ad55d5d27b9e.png)

Outgoing:
![image](https://user-images.githubusercontent.com/7191115/107607721-a1c7f200-6bff-11eb-8d71-19a4cb28c47f.png)
![image](https://user-images.githubusercontent.com/7191115/107607742-b7d5b280-6bff-11eb-8d4c-09b6299e6a12.png)

System Info:
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.13-2-MANJARO
OS Type: 64-bit
Processors: 12 × AMD Ryzen 5 2600X Six-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: GeForce GTX 1060 6GB/PCIe/SSE2
Kmail Version: 5.16.2 (20.12.2)
Hydroxide Version: 0.2.17

**Comment by ciiron** [comment]
for IMAP: no encryption, strip `@protonmail.com` from username

**Comment by NovaViper** [comment]
@ciiron Thanks man! I finally got it working. Say, is there a way to have it use TLS/SSL? Wouldn't not using the encryption make it insecure?

**Comment by ciiron** [comment]
It's all on your own machine/network, so unless you're exposing the ports to the internet (why?), you shouldn't have anything to worry about.

**Comment by NovaViper** [comment]
Ok, thanks!

**Comment by coffseducation** [comment]
> @ciiron Thanks man! I finally got it working. Say, is there a way to have it use TLS/SSL? Wouldn't not using the encryption make it insecure?

Hey!
Could you please tell me how you got smtp working?
Thanks!

**Comment by NovaViper** [comment]
> > @ciiron Thanks man! I finally got it working. Say, is there a way to have it use TLS/SSL? Wouldn't not using the encryption make it insecure?
> 
> Hey! Could you please tell me how you got smtp working? Thanks!

I actually don't remember how I had it working... I'm using the official bridge now since I upgraded my account and also using Mu4e (Mu for Emacs) for my email instead of Kontact, I say refer to what @suaviloquence said [earlier](https://github.com/emersion/hydroxide/issues/153#issuecomment-787511304) as that seems to be what fixed the issue for me then.

**Comment by suaviloquence** [comment]
> Hey! Could you please tell me how you got smtp working? Thanks!

@coffseducation,
I'm using thunderbird now, but I have the username as the email without `@protonmail.com` (or .ch), the password as the bridge password, no connection security and plaintext password.

**Comment by coffseducation** [comment]
Thanks guys!

Running ./hydroxide smpt -debug gets it working for me.

I just need to figure out how to auto-start it on boot now.
