### ISSUE TITLE
Feature Idea: Option to restrict auth to certain usernames

### ISSUE THREAD

**Issue by toluschr** [emersion/hydroxide#158]
As I plan on additionally running a hydroxide instance on my mail-server, I don't wan't everyone to be able to send email using my server.
A nice addition would be an option to restrict usernames for authenticating / sending mail.

**Comment by emersion** [comment]
Only usernames which have executed the `hydroxide auth` command can authenticate.

**Comment by toluschr** [comment]
I must have had some old configs left on my pc when testing. Sorry for the inconvenience.
