### ISSUE TITLE
carddav: no support for QueryAddressObjects

### ISSUE THREAD

**Issue by sbinet** [emersion/hydroxide#159]
it seems support for QueryAddressObjects is missing from the `carddav` proxy:

```go
func (b *backend) QueryAddressObjects(query *carddav.AddressBookQuery) ([]carddav.AddressObject, error) {
	panic("TODO")
}
```
https://github.com/emersion/hydroxide/blob/v0.2.17/carddav/carddav.go#L265

would an implementation piggy-backing on `ListAddressObjects` (to get the full list of addresses) and applying the query be suitable? (optionally, if `query==nil`, return the full list, so one could get started filtering off-hydroxide)

**Comment by emersion** [comment]
ProtonMail doesn't seem to have an endpoint to search contacts, so yeah, doing the filtering client-side is probably as good as it's going to get. Note, the max page size for `/api/contacts` seems to be 1000.

Pull requests welcome!

**Comment by emersion** [comment]
Can probably do something similar to `ListAddressObjects`.

https://github.com/emersion/hydroxide/blob/5e211c61accdb1eb2796022017cffea64703355c/carddav/carddav.go#L200

And maybe look into extracting the common code into a helper function if that makes sense.

**Comment by sbinet** [comment]
ok.

**Comment by sbinet** [comment]
perhaps the filtering/matching could be done in `github.com/emersion/go-webdav/carddav`?

something like:
```go
package carddav

func (query *AddressBookQuery) Match(ao AddressObject) (bool, error) { ... }
```

**Comment by emersion** [comment]
Ah, yes, having such an helper would be a good idea, I agree.
