### ISSUE TITLE
Documentation typo?

### ISSUE THREAD

**Issue by joshrsmith** [emersion/hydroxide#16]
The README.md indicates to use this to install: `go get github.com/emersion/hydroxide` but that results in "can't load package: package github.com/emersion/hydroxide: no Go files in /home/josh/go/src/github.com/emersion/hydroxide"

I think it should say: `go get github.com/emersion/hydroxide/cmd/hydroxide` ?

**Comment by emersion** [comment]
Yeah, you're right, thanks for spotting this issue! Do you mind sending a pull request?
