### ISSUE TITLE
SMTP Settings NextCloud

### ISSUE THREAD

**Issue by BBurkhardt** [emersion/hydroxide#162]
I'm trying to use hydroxide to connect my ProtonMail account with my NextCloud instance running on the same "headless" sbc.

In NextCloud I provided the following information in the respective fields:

Encryption: `none`
Sender: `<user>@protonmail.com`
Authenticationmethod: `login`
Authentication necessary: `check`
Server: `localhost`
Port: `1025`
User: `<user>`
SMTP-Password: `<hydroxide password>`

On testing the setup I receive an error message: 

> Failed to authenticate on SMTP server with username "user" using 0 possible authenticators.

Is that a NextCloud issue?

**Comment by emersion** [comment]
What are the other choices for "authentication method"?

**Comment by BBurkhardt** [comment]
The other options are

- STARTTLS 
- SSL/TLS

**Comment by emersion** [comment]
These sound like encryption options.

**Comment by BBurkhardt** [comment]
My bad, sorry, I edited my comment.

**Comment by emersion** [comment]
Try "Plain text".

"Login" is a legacy, non-standard Microsoft mechanism.

**Comment by BBurkhardt** [comment]
Thanks a bunch! This worked!

**Comment by emersion** [comment]
No problem
