### ISSUE TITLE
Tor-Support

### ISSUE THREAD

**Issue by fisch2** [emersion/hydroxide#163]
Would it be possible to at add an option to configure the api endpoint, so that hydroixide can use the tor hidden service https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/api instead of https://mail.protonmail.com/api ? Of course the user would have to setup the tor daemon and the proxy variable.

**Comment by emersion** [comment]
Yeah, that sounds reasonable. I'm not sure what the best option would be: env variable? CLI option? Some kind of auto-detection that `.onion` domain names can be resolved? Something else?

**Comment by 4n0nym0u53** [comment]
I think auto-detection could be an option, maybe by pinging the .onion URL of Tor Project or something (obviously there should be some fallback sites, in case Tor Project is down or something). I think the user would typically run hydroxide with something like torsocks in such case.

**Comment by fisch2** [comment]
In that case, i think we should try to ping the tor hidden service of proton (protonirockerxow.onion), because thats what we want to access anyway and there is no point in trying to access a different onion service, if we want to check for the availability. Also i'm unsure about using an auto-detection, because you may not want the system to silently fail to use tor and try to connect via the clearweb, if the connection via tor fails.

**Comment by 4n0nym0u53** [comment]
That sounds reasonable. Also, in case hydroxide is unable to connect to `https://protonirockerxow.onion/api`, it should ask the user whether they want to connect using the clearnet domain instead (preferably still over Tor).

Sidenote: Do you know if ProtonMail have a v3 `.onion` domain yet?

**Comment by fisch2** [comment]
They don't, otherwise their .onion adress would be a lot longer. Hopefully they switch to v3 in time, before version 0.4.6 releases in october. This is also a little bit more complicated, because they will also need to get a new certificate from digicert in time.

**Comment by 4n0nym0u53** [comment]
I see. It is in fact the deprecation of v2 `.onion` addresses I'm concerned about.

**Comment by fisch2** [comment]
Seems like Protonmail has now added an v3 `.onion` adress. https://protonmail.com/tor has a link to the new v3 `.onion` adress: https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/ We should therefore use the new one. I updated my original comment accordingly.

**Comment by emersion** [comment]
> using a command line option to change the api endpoint

Looks like a good idea to me.

**Comment by h3xagonal** [comment]
Did not realiase this issue already exists. Silly me.

Something to note is that the new ProtonMail onion now appears to have feature-pairty with the clearnet web-client and is not out-of-date anymore. Have not tested in depth but API endpoints appear to work

Thank you.
