### ISSUE TITLE
Plain text message (Evolution)

### ISSUE THREAD

**Issue by zarandya** [emersion/hydroxide#164]
Evolution has the option to view incoming messages as plain text instead of html if possible. It works well with most providers but not with hydroxide. Could this be fixed as this is the only way to get a full dark theme in Evolution

**Comment by emersion** [comment]
Unfortunately ProtonMail doesn't seem to retain the plain-text copy when an incoming email has an HTML part. Or at least last time I looked at the API there was no way to retrieve it.

**Comment by zarandya** [comment]
Ah I see. Would it be possible to generate the plain text from the html? Removing the <...> tags would probably be a good approximation for most messages.

**Comment by emersion** [comment]
No, I don't believe this is a desirable feature, sorry.
