### ISSUE TITLE
SMTPDeliveryError: 554 b'5.0.0 Error: transaction failed, blame it on the weather: message: unhandled charset "utf8"'

### ISSUE THREAD

**Issue by tgunnoe** [emersion/hydroxide#165]
Probably related to this https://github.com/emersion/hydroxide/issues/116

**Comment by emersion** [comment]
This encoding should be handled by https://github.com/golang/text/blob/e3aa4adf54f644ca0cb35f1f1fb19b239c40ef04/encoding/htmlindex/tables.go#L97

**Comment by tgunnoe** [comment]
You're suggesting the problem lies outside of hydroxide? or where to look for the fix within it

**Comment by emersion** [comment]
This error comes from go-message.

**Comment by tgunnoe** [comment]
Is this something that needs to be fixed in hydroxide, or are you saying its how i'm running it (eg go version)

**Comment by emersion** [comment]
Probably a bug in hydroxide. Patches welcome.

**Comment by emersion** [comment]
<div class="timeline-comment-header clearfix "><h3 class="timeline-comment-header-text f5 text-normal"><a href="https://github.com/emersion/hydroxide/pull/177#issuecomment-851307284" id="issuecomment-851307284-permalink" class="Link--secondary js-timestamp"><relative-time datetime="2021-05-31T08:20:47Z" class="no-wrap" title="May 31, 2021, 10:20 AM GMT+2">now</relative-time></a>


    <span class="js-comment-edit-history">
    </span>
  </h3>
</div>


      <div class="edit-comment-hide">
          

        
<task-lists sortable="">

  
    
      
          "utf8" is non-standard. This is a bug in your email client.</task-lists></div>
