### ISSUE TITLE
Decrypt encrypted password

### ISSUE THREAD

**Issue by user18130814200115-2** [emersion/hydroxide#169]
Say one would be really stupid and forget their protonmail login password (not me of course). But still be logged in with hydroxide and have access to the bridge password.
Can this hypothetical person get their protonmail login password from the encrypted version stored by hydroxide?  if so, how?

**Comment by emersion** [comment]
Yes. By decrypting hydroxide's crendetials file with the bridge password.

**Comment by user18130814200115-2** [comment]
But what encryption scheme is used?
How would I go about doing this?

**Comment by user18130814200115-2** [comment]
I looked through he code and figured it out, thank you
