### ISSUE TITLE
In-Reply-To headers missing

### ISSUE THREAD

**Issue by Tooniis** [emersion/hydroxide#186]
I'm using hydroxide with git send-email to send patches to the LKML. Sending single patches is fine, but patch series need to have an In-Reply-To header in each patch pointing to the cover letter, which hydroxide is not adding. Here are some examples of patches I sent with hydroxide:

1. Cover letter: https://lore.kernel.org/linux-arm-msm/1psXpLs4s2ivJ6uAXr4TiLbs2gmwRfTVjcyzG68k@cp3-web-021.plabs.ch/
    A patch from the series: https://lore.kernel.org/linux-arm-msm/fzmn8bdpxO41bpKxyI7aD2zwEqKGGRVC3DhcM9EWY@cp3-web-020.plabs.ch/
2. Cover letter: https://lore.kernel.org/lkml/a1IcsWeSdRxWaMFcwV1k7z3l1HaAkyRCo2zLdOWb8w@cp4-web-014.plabs.ch/
    A patch from the series: https://lore.kernel.org/lkml/W4cbBtSKsvNY8PoUe5j75MtKCqkxYop7f0WBuSsjnM@cp4-web-038.plabs.ch/

You can append `raw` to any of the links to get a mbox file with all the headers.

git is indicating in the send log that it added the header, so I don't think the issue is there.

**Comment by emersion** [comment]
Yeah, I've been hitting this as well. An attempt at fixing this is in https://github.com/emersion/hydroxide/pull/155 but is not yet working.

**Comment by emersion** [comment]
Apparently the ProtonMail API now allows us to set the Message-Id header field for outgoing messages, so we should behave better now!
