### ISSUE TITLE
Messages in outbox not synced with Geary

### ISSUE THREAD

**Issue by julianfairfax** [emersion/hydroxide#187]
I've used this bridge to access my ProtonMail through Geary on Linux. It works great for receiving messages but when I send them, Geary puts them into it's outbox, which isn't synced to ProtonMail through the bridge, and causes Geary to not know what to do with the email after it's been sent. Hopefully this issue can fixed. Thanks for your work on this wonderful tool!

**Comment by julianfairfax** [comment]
I've also opened an issue for Geary for an option to disable the Outbox. https://gitlab.gnome.org/GNOME/geary/-/issues/1278

**Comment by julianfairfax** [comment]
I've decided to just use the officially supported web version of ProtonMail so this isn't an issue for me anymore.

**Comment by julianfairfax** [comment]
The issue here is the same as I'm now experiencing on Thunderbird, and that you described somewhere, which is that you can only write to the drafts folder (I'm experimenting an issue with that on Thunderbird now though too). I'm not sure if this is something you can fix in hydroxide or not but I've just turned off the feature (and saved drafts locally for the other one) for now in Thunderbird.

**Comment by julianfairfax** [comment]
Reopening since I'm using Geary again and these issues are still present.

**Comment by julianfairfax** [comment]
You mentioned somewhere that you can only write to the drafts folder on ProtonMail. I'm not sure if this is something you can fix in hydroxide then?

**Comment by julianfairfax** [comment]
I fixed it. Turns out I just had to change save_sent to false in .var/app/org.gnome.Geary/config/geary/account_04/geary.ini

**Comment by maymage** [comment]
This could (have) cause(d)

* https://gitlab.gnome.org/GNOME/geary/-/issues/1276
