### ISSUE TITLE
Hydroxide not listening to right hostname

### ISSUE THREAD

**Issue by RonaldPhilipsen** [emersion/hydroxide#188]
OS: Alpine linux

```
/opt/hydroxide # ./hydroxide smtp -debug -stmp-host 10.0.1.14
2021/08/03 15:22:34 SMTP server listening on 127.0.0.1:1025
```

**Comment by emersion** [comment]
Move `smtp` at the end of the arguments like so:

```
./hydroxide -debug -stmp-host 10.0.1.14 smtp
```

Yes, it's confusing. Patches welcome to improve argument parsing.

**Comment by RonaldPhilipsen** [comment]
Gotcha thanks! I haven't touched go yet but if i find the time i'll look into it!
