### ISSUE TITLE
Rasbian compatible binaries

### ISSUE THREAD

**Issue by kachapman** [emersion/hydroxide#189]
I have a Nextcloud server on my Pi4 and I want to use the mail feature to start receiving my proton mail. I currently use PM through Mailspring on my Pop!OS install with the bridge. 
Im trying to figure out how to build this binary using the go language, but Im struggling. Does anyone have an arm64 binary available that I could use instead?

**Comment by emersion** [comment]
Sorry, but there are no binaries, nor any plans to provide them.
