### ISSUE TITLE
-bash: hydroxide: command not found

### ISSUE THREAD

**Issue by kachapman** [emersion/hydroxide#190]
I'm getting this error after installing:

> -bash: hydroxide: command not found

go version:

> go version go1.17 linux/arm64

![image](https://user-images.githubusercontent.com/63679503/129847026-432ac379-3a98-49c1-988d-e23747083ce6.png)

Thanks in advance.

**Comment by kachapman** [comment]
If I use ./hydroxide it works. But now I am getting an authorization error.

> openpgp: invalid data: private key checksum failure

 I've double checked my password to make sure it was entered correctly. 
If I start the bridge with "./hydroxide" will it still be persistently running in the background after a server restart?

**Comment by emersion** [comment]
"private key checksum failure" usually indicates a bad password.
