### ISSUE TITLE
Status of project / target users?

### ISSUE THREAD

**Issue by xanoni** [emersion/hydroxide#192]
**Q: Why would a technical user NOT choose hydroxide, but prefer the official bridge for a bit longer?** 

I've read through many of the tickets here and believe to have a high level sense of what the rough edges are that are still left to be tackled. However, I would also be curious to know how people who have spent some time working on the code and/or who have been active users of hydroxide judge the current status of the project. Thank you.

**Comment by emersion** [comment]
Status: needs more love, especially on the SMTP and CardDAV/CalDAV side of things.

Closing because this isn't a bug report.
