### ISSUE TITLE
"HOME not set" trying to login

### ISSUE THREAD

**Issue by LuisAlfredo92** [emersion/hydroxide#196]
After trying to login I get the message "HOME not set":

> ./hydroxide auth xxx@protonmail.com
> Password:
> 2FA TOTP code: xxx
> 2021/09/25 14:17:21 HOME not set

I'm on Windows. Do I have to create a Environment variable "HOME" with the path to Hydroxide?
However, after this and some problems with Go I also wanted to ask, isn't this software Linux exclusive?

**Comment by emersion** [comment]
I don't officially support Windows, but if you have generic patches (e.g. using `os.UserConfigDir`) I'll merge them.
