### ISSUE TITLE
failed to unlock any key

### ISSUE THREAD

**Issue by bknow1452** [emersion/hydroxide#197]
Hy everybody,

did an OS update of my Raspberry PI and rebooted it. Afterwards i received an error from my nextcloud instance which is using hydroxide as IMAP Bridge

`failed to unlock any key`

So i had a look at my bridge, restarted it and and again

`failed to unlock any key`

once nextcloud or any other service using the bridge tried to send en e-mail.

I tried to re-authenticate but receive this:

`Password:
2FA TOTP code: XXXXXX
2021/11/21 14:54:11 warning: failed to unlock key "name1@domain.tld" PGPHERE: openpgp: invalid data: private key checksum failure
2021/11/21 14:54:11 warning: failed to unlock key "name2@domain.tld" PGPHERE: openpgp: invalid data: private key checksum failure
2021/11/21 14:54:11 warning: failed to unlock key "name3@domain.tld" PGPHERE: openpgp: invalid data: private key checksum failure
2021/11/21 14:54:11 warning: failed to unlock key "name4@domain.tld" PGPHERE: openpgp: invalid data: private key checksum failure
2021/11/21 14:54:11 failed to unlock any key
`

What i tried so far:

 - (re)moved  ~/.config/hydroxide files and re-authenticate - no success, same error
 - rebuild hydroxide from scratch (git clone, go build...) and re-authenticate - no success, same error
 - build and re-authenticate hydroxide on x86_64 Linux System (Arch Linux) - no succes, same error 
 - activate 2FA in Protonmail, because i thought it might be helping - no success, same error
 - changed my Password in Protonmail - no success, same error

How can i contribute and deliver more input (e.g. -debug, some log i dont know, etc.) to help you with that?

regards

**Comment by emersion** [comment]
Does this help?

https://github.com/emersion/hydroxide/commit/5eadb35c67c542e5e5b5b3034bead5730ab2263e

**Comment by bknow1452** [comment]
> Does this help?
> 
> [5eadb35](https://github.com/emersion/hydroxide/commit/5eadb35c67c542e5e5b5b3034bead5730ab2263e)

Hey @emersion ,

did a git pull and go build and its working like a charm :-) . Thanks for the quick fix

regards
