### ISSUE TITLE
554 Error: transaction failed, blame it on the weather: unknown sender address

### ISSUE THREAD

**Issue by apiote** [emersion/hydroxide#20]
This is the only result I get when trying to send anything. I tried with Mutt, plain msmtp, ClawsMail, sendEmail.

example (values in `[]` are hidden by me); hydroxide runs in background and reports nothing apart from `Starting SMTP server at 127.0.0.1:1465`:

```
$ sendEmail -f '[login]@protonmail.com' -t '[receiver]' -m 'test' -s localhost:1465 -l /tmp/smtp.log -xu '[login]' -xp '[password]' -vvv
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => Connecting to localhost:1465
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => My IP address is: 127.0.0.1
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Checking for SMTP success or error status in the message: 220 localhost ESMTP Service Ready
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Found SMTP success code: 220
Jan 09 13:24:21 localhost sendEmail[15925]: SUCCESS => Received: 	220 localhost ESMTP Service Ready
Jan 09 13:24:21 localhost sendEmail[15925]: INFO => Sending: 	EHLO localhost.localdomain
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Checking for SMTP success or error status in the message: 250-Hello localhost.localdomain
250-PIPELINING
250-8BITMIME
250 AUTH PLAIN
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Found SMTP success code: 250
Jan 09 13:24:21 localhost sendEmail[15925]: SUCCESS => Received: 	250-Hello localhost.localdomain
250-PIPELINING
250-8BITMIME
250 AUTH PLAIN
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => The remote SMTP server does NOT support TLS :(
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => SMTP-AUTH: Using PLAIN authentication method
Jan 09 13:24:21 localhost sendEmail[15925]: INFO => Sending: 	AUTH PLAIN [authentication]
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Checking for SMTP success or error status in the message: 235 Authentication succeeded
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Found SMTP success code: 235
Jan 09 13:24:22 localhost sendEmail[15925]: SUCCESS => Received: 	235 Authentication succeeded
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => User authentication was successful (Method: PLAIN)
Jan 09 13:24:22 localhost sendEmail[15925]: INFO => Sending: 	MAIL FROM:<[login]@protonmail.com>
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Checking for SMTP success or error status in the message: 250 Roger, accepting mail from <[login]@protonmail.com>
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Found SMTP success code: 250
Jan 09 13:24:22 localhost sendEmail[15925]: SUCCESS => Received: 	250 Roger, accepting mail from <[login]@protonmail.com>
Jan 09 13:24:22 localhost sendEmail[15925]: INFO => Sending: 	RCPT TO:<[receiver]>
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Checking for SMTP success or error status in the message: 250 I'll make sure <[receiver]> gets this
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Found SMTP success code: 250
Jan 09 13:24:22 localhost sendEmail[15925]: SUCCESS => Received: 	250 I'll make sure <[receiver]> gets this
Jan 09 13:24:22 localhost sendEmail[15925]: INFO => Sending: 	DATA
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Checking for SMTP success or error status in the message: 354 Go ahead. End your data with <CR><LF>.<CR><LF>
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Found SMTP success code: 354
Jan 09 13:24:22 localhost sendEmail[15925]: SUCCESS => Received: 	354 Go ahead. End your data with <CR><LF>.<CR><LF>
Jan 09 13:24:22 localhost sendEmail[15925]: INFO => Sending message body
Jan 09 13:24:22 localhost sendEmail[15925]: Setting content-type: text/plain
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Checking for SMTP success or error status in the message: 554 Error: transaction failed, blame it on the weather: unknown sender address
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Found SMTP error code: 554
Jan 09 13:24:22 localhost sendEmail[15925]: ERROR => Received: 	554 Error: transaction failed, blame it on the weather: unknown sender address

```

**Comment by emersion** [comment]
Hmmm, it seems that your sender email `[login]@protonmail.com` is not recognized.

The error is triggered here: https://github.com/emersion/hydroxide/blob/2c300de8cd1854656017e822d516c7b73d754eee/smtp/smtp.go#L74

Can you add `fmt.Println(addr)` line 68? That'll print all addresses valid for this user.

**Comment by apiote** [comment]
Thank You.

Turns out, I was using case insensitive address (all small letters) while Hydroxide explicitly needs the very same—case sensitively—address that is registered at ProtonMail.

**Comment by emersion** [comment]
Let's replace that by a case-insensitive match.

**Comment by apiote** [comment]
I get this error again. This time (in smtp/smtp.go) `fromAddr` is `<nil>` (line 67) and `addr` in loop (lines 68–73) cannot be printed (as if the loop wasn’t run at all).

This may be due to another changes n API (I have no idea). Will You reopen this issue or shall I open a new one?

**Comment by emersion** [comment]
Yeah, I get this error too.

**Comment by harleylang** [comment]
I'm not trying to unearth this because I understand it is closed, but I solved the common `failed to read private key: openpgp: unsupported feature: public key type: 22` mentioned in #46 because I realized I authorized one email address, but tried sending with an alias. it might be worth-while to create an FAQ section of the readme that asks users to double check that they are sending from their authorized address and not an unauthorized alias.

**Comment by emersion** [comment]
What is an "unauthorized alias"? Sending from an alias should work too.

**Comment by harleylang** [comment]
One that is not logged into / authorized by hydroxide

**Comment by emersion** [comment]
You only need to login once for all your aliases and addresses

**Comment by harleylang** [comment]
That was not my experience with python and smptlib.

**Comment by harleylang** [comment]
However, perhaps it was due to the RSA keys that I mentioned in #46 and I attributed this problem.

**Comment by Ultracoolguy** [comment]
I'm having a very similar issue to this. I'm trying to use `git send-email` when this error happens:

     5.0.0 Error: transaction failed, blame it on the weather: unknown sender address

However, on the log of `hydroxide smtp`:

    2020/10/09 11:35:45 user logged in

My relevant .gitconfig settings:

     [user]
	     name = Ultracoolguy
	     email = user@protonmail.org
     [sendemail]
	     smtpserver = localhost
	     smtpencryption = none
	     smtpuser = user
	     smtpserverport = 1025`

(Ofc, my actual username isn't "user")

**Comment by emersion** [comment]
This likely means `sendemail.smtpuser` is correct, but `user.email` isn't.

**Comment by Ultracoolguy** [comment]
Ahh, I know what happened. I typed ".org" instead of ".com".

Thanks for pointing me in the right direction!
