### ISSUE TITLE
504 5.7.4 Unsupported authentication mechanism

### ISSUE THREAD

**Issue by sebas05000** [emersion/hydroxide#203]
Good Evening When I am trying to send a test message over SMTP from my Synology NAS I get this error.

![image](https://user-images.githubusercontent.com/66391171/157350564-063e5307-ccc7-402b-8b7d-5d6c350a58c1.png)

Hydroxide is installed on Linux Mint

**Comment by emersion** [comment]
LOGIN is a non-standard authentication mechanism. Clients must use PLAIN instead.

**Comment by sebas05000** [comment]
Thanks for letting me know sadly I wanted to use as notifications for my NAS as well some Docker Containers.

Do you know a way to modify and add or force to use plain instead of login? or to know how to add it myself to hydroxide?
