### ISSUE TITLE
hydroxide: command not found

### ISSUE THREAD

**Issue by coffseducation** [emersion/hydroxide#205]
hydrixide command for username not recognised!

~/hydroxide$GO111MODULE=on go build ./cmd/hydroxide
go: downloading github.com/ProtonMail/go-crypto v0.0.0-20211112122917-428f8eabeeb3
go: downloading github.com/emersion/go-imap-specialuse v0.0.0-20201101201809-1ab93d3d150e
go: downloading github.com/emersion/go-imap-move v0.0.0-20210907172020-fe4558f9c872
go: downloading github.com/emersion/go-mbox v1.0.2
go: downloading github.com/emersion/go-imap v1.2.0
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading golang.org/x/crypto v0.0.0-20211117183948-ae814b36b871
go: downloading github.com/emersion/go-message v0.15.0
go: downloading github.com/emersion/go-webdav v0.3.1
go: downloading golang.org/x/sys v0.0.0-20211117180635-dee7805ff2e1
go: downloading github.com/emersion/go-smtp v0.15.0
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/emersion/go-bcrypt v0.0.0-20170822072041-6e724a1baa63
go: downloading github.com/emersion/go-textwrapper v0.0.0-20200911093747-65d896831594
go: downloading github.com/emersion/go-vcard v0.0.0-20210521075357-3445b9171995
go: downloading golang.org/x/term v0.0.0-20210927222741-03fcf44c2211
go: downloading github.com/emersion/go-sasl v0.0.0-20211008083017-0b9dcfb154ac
go: downloading github.com/boltdb/bolt v1.3.1
anarcho@LuNoHo:~/hydroxide$hydroxide auth myprotonusername
hydroxide: command not found

**Comment by emersion** [comment]
This builds the executable in the current directory.

**Comment by coffseducation** [comment]
ah, ok

./hydroxide auth myusername

Thanks.
