### ISSUE TITLE
Incorrect login error

### ISSUE THREAD

**Issue by skyemk** [emersion/hydroxide#209]
![image](https://user-images.githubusercontent.com/88494287/162051947-78069551-3c5d-49f4-a487-58ddb9647328.png)

**Comment by emersion** [comment]
Well. Your credentials are incorrect. The error comes from ProtonMail.

**Comment by skyemk** [comment]
cant be possible? i logged into the website just now.

**Comment by emersion** [comment]
Do you have 2FA setup? If not, no idea why this would happen.

**Comment by skyemk** [comment]
i dont have 2fa enabled

**Comment by skyemk** [comment]
even with multiple rebuilds still the same, Ill give a password change and try i guess

**Comment by skyemk** [comment]
okay that worked lol
