### ISSUE TITLE
Login failed Captcha required

### ISSUE THREAD

**Issue by dyrehaugen** [emersion/hydroxide#230]
Trying to install hydroxide, but first login fails.

jmh@YZDOG:~/go/src/github.com/hydroxide$ ./hydroxide auth dyrehaugen
Password:
2022/09/29 19:26:44 request failed: POST https://mail.proton.me/api/auth: [9001] For sec\
urity reasons, please complete captcha. If you can't pass it, please try updating your a\
pp or contact us here: https://proton.me/support/abuse
2022/09/29 19:26:44 [9001] For security reasons, please complete captcha. If you can't p\
ass it, please try updating your app or contact us here: https://proton.me/support/abuse

Suggestions appreciated

**Comment by CapitalHitman** [comment]
> Trying to install hydroxide, but first login fails.
> 
> jmh@YZDOG:~/go/src/github.com/hydroxide$ ./hydroxide auth dyrehaugen Password: 2022/09/29 19:26:44 request failed: POST https://mail.proton.me/api/auth: [9001] For sec urity reasons, please complete captcha. If you can't pass it, please try updating your a pp or contact us here: https://proton.me/support/abuse 2022/09/29 19:26:44 [9001] For security reasons, please complete captcha. If you can't p ass it, please try updating your app or contact us here: https://proton.me/support/abuse
> 
> Suggestions appreciated

I am experiencing the exact same issue.
