### ISSUE TITLE
app: how to add the app to "autostart" on linux?

### ISSUE THREAD

**Issue by gucio321** [emersion/hydroxide#233]
I've tried adding it to `.bash_profile`, but, since bash_profile waits for exit status, gnome-session failed to load at all
how to do this correctly?

**Comment by dvalter** [comment]
If your system runs systemd, you may add user service to `/etc/systemd/user` or `~/.config/systemd/user` with the following content **(use your hydroxide binary path)** and it should run hydroxide on login more reliably than with bashrc/bash_profile.
```
[Unit]
Description=Hydroxide (Protonmail proxy) service

[Service]
ExecStart=/path/to/hydroxide serve
Type=simple
Restart=always
RestartSec=30

[Install]
WantedBy=default.target
```

**Comment by gucio321** [comment]
okey, it works, thank you!
