### ISSUE TITLE
Document the undocumented options

### ISSUE THREAD

**Issue by bruceleerabbit** [emersion/hydroxide#237]
It’s clear from other bug reports that an `HTTPS_PROXY` variable is recognized and treated (though I think mistreated ATM). In any case, that variable should be mentioned on the `--help` page.

The `--help` page also neglects to mention that a session ID cookie can be passed as an argument to the “auth” command.

**Comment by emersion** [comment]
> It’s clear from other bug reports that an HTTPS_PROXY variable is recognized and treated (though I think mistreated ATM). In any case, that variable should be mentioned on the --help page.

That's the standard Go library's doing. hydroxide has no special code for this.

> The --help page also neglects to mention that a session ID cookie can be passed as an argument to the “auth” command.

Nope, cookies aren't accepted.

**Comment by bruceleerabbit** [comment]
> > The --help page also neglects to mention that a session ID cookie can be passed as an argument to the “auth” command.
> 
> Nope, cookies aren't accepted.

If that’s true, contrary to what @dvalter says here:

https://github.com/emersion/hydroxide/issues/179#issuecomment-855283386

then that’s yet another bug. Why are illegal parameters not triggering a syntax error?

**Comment by emersion** [comment]
This comment is about a fork.

**Comment by bruceleerabbit** [comment]
> This comment is about a fork.

But I’m not running a fork. I’m running the emersion/hydroxide version as follows:
```
HTTPS_PROXY='socks5://127.0.0.1:9050' hydroxide -api-endpoint https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/api auth "$UID" "$sessionID"
```
If the $sessionID is only supported in the fork, then the version I have should terminate with a syntax error saying something like “too many args”.

**Comment by acheong08** [comment]
I made a [fork](https://github.com/acheong08/hydroxide) for my own use.

Some changes:
- Merged pull requests I found helpful:
 - #247
 - #138
 - #257
- Added some options I needed:
 - ```
   -config-home string
    	Path to the directory where hydroxide stores its configuration
   -proxy-url string
    	HTTP proxy URL (e.g. socks5://127.0.0.1:1080)
```
- Bumped dependencies and fixed compatibility issues: https://github.com/acheong08/hydroxide/pull/4/commits/56a9324f8e7d655cddb8d3a7b02d4a0ccb5823ad
