### ISSUE TITLE
(security) alternative needed for HTTPS_PROXY variable (a CLI option)

### ISSUE THREAD

**Issue by bruceleerabbit** [emersion/hydroxide#238]
There is a security issue with using the HTTPS_PROXY variable. Suppose you mistype the variable name (which is very easy to do because there are 4 common variations of that variable name). Hydroxide has no clue that you intend to use a proxy, so it will simply ignore the malformed variable and connect ***over the normal clearnet***. That mere connection alone can be sensitive, and worse: the user doesn’t even know about the error. Variables require users to have a leap of faith that the variable is even read.

So for security there should also be a CLI option. If the option is mis-typed, hydroxide will terminate with a syntax error. If the option is correctly typed but there is a problem with the proxy server, hydroxide at least knows the user intends to proxy the connection and can fail-safe (terminate) in that case as well.

Related bug: apparently the variable was implemented under bug #110.

**Comment by emersion** [comment]
Not interested in this, sorry.
