### ISSUE TITLE
imap: expose custom labels/folders as mailboxes

### ISSUE THREAD

**Issue by emersion** [emersion/hydroxide#24]

**Comment by vogelfreiheit** [comment]
Seconded! This is quite relevant.

**Comment by emersion** [comment]
Folders are now exposed as mailboxes. I plan to add labels support as IMAP flags.

**Comment by emersion** [comment]
Labels are now exposed as flags.

**Comment by AckslD** [comment]
@emersion I just setting up and trying out hydroxide. However, I'm not sure how to see the custom labels as IMAP flags as you mention. For example I'm trying to use aerc + notmuch. How can I see the labels/flags/tags? Using %Z or %g in the index-format does not show my custom labels.

**Comment by emersion** [comment]
I don't know/use notmuch, but from the [docs](https://notmuchmail.org/software/):

> Internet Mail Access Protocol servers that can interoperate with notmuch. It is of note that IMAP protocol supports storing so-called keywords (user-defined flags) which are mostly equivalent to notmuch tags. Unfortunately Maildir does not have standard way to encode keywords, so there are extensions necessary to store that information.

It seems to depend on the mail fetcher. offlineimap probably won't work, muchsync and dsync may work.

**Comment by AckslD** [comment]
Ah okay! Thanks! I was trying with offlineimap, I'll try with another mail fetcher :+1:. I'll let you know how it goes.

**Comment by AckslD** [comment]
Actually, I tried using either IMAP, maildir or notmuch as backend for aerc and not sure how to see the labels in any case.

**Comment by emersion** [comment]
aerc doesn't support custom labels with its IMAP backend yet. Not sure about notmuch. Maildir won't support them either.

**Comment by AckslD** [comment]
I see, thanks for the information!
