### ISSUE TITLE
`auth` fails with "This webpage is out of date"

### ISSUE THREAD

**Issue by Akiiino** [emersion/hydroxide#245]
Whenever I try to `hydroxide auth`, I get the following output --- no matter the login and password I provide. Did the API change or something?

```2023/03/02 20:38:10 request failed: POST https://mail.proton.me/api/auth/info: [5003] This webpage is out of date, please refresh the page to continue using it
2023/03/02 20:38:10 [5003] This webpage is out of date, please refresh the page to continue using it```

**Comment by emersion** [comment]
Should be fixed by https://github.com/emersion/hydroxide/commit/4cb15fbdf3555e5d1bfc95eece5086fc69aa4f74

**Comment by Akiiino** [comment]
So it does :)

**Comment by k2helix** [comment]
> Should be fixed by [4cb15fb](https://github.com/emersion/hydroxide/commit/4cb15fbdf3555e5d1bfc95eece5086fc69aa4f74)

Using hydroxide on Termux gives this output, maybe the pkg was not updated?

**Comment by eternal-sorrow** [comment]
Need a release with a fix to this.

**Comment by emersion** [comment]
Done.

**Comment by eternal-sorrow** [comment]
Thank you!
