### ISSUE TITLE
Cannot authorise, openpgp error

### ISSUE THREAD

**Issue by underthecocotree** [emersion/hydroxide#25]
I seem to have a problem authorising, despite the fact that use the right credentials. Can you help out with the following?

```
hydroxide auth username
Password:
Mailbox password:
2018/01/29 09:42:16 openpgp: invalid data: private key checksum failure
```

Thanks!

**Comment by emersion** [comment]
I hadn't tested two password mode. This should be fixed now!

**Comment by underthecocotree** [comment]
Works fine now. Thanks!

I had to:
```
go get -u all
# or I guess
go get -u hydroxide
```
