### ISSUE TITLE
auth command returns 403 token scope issue

### ISSUE THREAD

**Issue by GilOliveira** [emersion/hydroxide#250]
Hi everyone! Running into an issue (installed 0.2.26), which is similar to other issues I've seen here (namely #68 and #97), but on the auth step.
After running `hydroxide auth <username>` and providing my password I immediately get this 403 error:

```
2023/04/13 13:04:52 request failed: GET https://mail.proton.me/api/keys/salts: [403] Access token does not have sufficient scope
2023/04/13 13:04:52 [403] Access token does not have sufficient scope
```

Curiously enough, my account is secured with 2FA (WebAuthn and TOTP both set up) and the command didn't prompt me for a TOTP code, made me a bit suspicious.

Running on macOS 13.3.1 (22E261).

Cheers.

**Comment by BertalanD** [comment]
Hey! I ran into this myself today. Could you please check if #251 fixes your issue, too?
