### ISSUE TITLE
Unable to connect after reboot

### ISSUE THREAD

**Issue by answer35** [emersion/hydroxide#256]
I am using hydroxide with thunderbird & k9 mail, all worked fine I was able to read my emails on both clients.
However, I made a service to be able to auto start hydroxide in case of reboot but after I did it, service started properly, status indicate that everything runs fine. To make sure everything is fine, I also run the command manually and it tells me that port is already in use so that's great. But now, thunderbird and K9 are not able to connect.

Is the password changes after a reboot ? Is there a command to show it ? I tried to make the auth command again but there is an error when typing password.

**Comment by answer35** [comment]
I decided to remake a full install to test but still, I am not able to use auth.
I receive that error:
`Post "https://mail.proton.me/api/auth/info": dial tcp 0.0.0.0:443: connect: connection refused`

**Comment by dvalter** [comment]
> I decided to remake a full install to test but still, I am not able to use auth. I receive that error: `Post "https://mail.proton.me/api/auth/info": dial tcp 0.0.0.0:443: connect: connection refused`

From this message, it looks like an issue with your network setup, more likely, the name resolution, and not with hydroxide: it just can't connect to PM

Check your DNS settings, hosts file or possibility or protonmail being censored

**Comment by answer35** [comment]
what I don't understand is that it was working with no issue this morning and nothing changed in config. Also if I recreate VM to make fresh install 100% identical to this morning, then it doesn't work. Still that error coming.
Is it possible that it has been "blocked" on Proton side regarding all tests I made ?
But I am still able to connect on website directly.

**Comment by answer35** [comment]
I finally changed DNS to 8.8.8.8 for testing and then I was able to authenticate. Looking on my DNS logs, it seems that a block list has been updated and is now blocking mail.proton.me so I will remove that blocking list and it should be fine, I hope
