### ISSUE TITLE
Login failure for IMAP and SMTP 

### ISSUE THREAD

**Issue by underthecocotree** [emersion/hydroxide#26]
Hi,

I am trying to setup the client to connect to the IMAP and the SMTP server but I have not been successful. I tried both thunderbird and apple's mail.app. I tried through the terminal as well but I had no luck. I tried to look at the source code to see if I could figure things out but no luck there either. 

I get the following error: `Verify that the username and password are correct.`

I managed to connect to the smtp without authentication but when I try to send an email it doesn't let me.

So here is what I have done
```
hydroxide auth MYUSERNAME
Password:
Bridge password:  base64__32_byte_password= 
#  I use the string above as my password
```

On different terminals I load imap and smtp
```
hydroxide imap
hydroxide smtp
```

I can use nc to connect to both servers
```
# IMAP
 nc 127.0.0.1 1143
* OK [CAPABILITY IMAP4rev1 AUTH=PLAIN] IMAP4rev1 Service Ready

# SMTP
nc 127.0.0.1 1025
220 localhost ESMTP Service Ready
ehlo localhost
250-Hello localhost
250-PIPELINING
250-8BITMIME
250 AUTH PLAIN
```

***

For the client set up I use the following:
**IMAP**
```
Username:  USERNAME (without @protonmail.com)
Password:  base64__32_byte_password= (I tried decoding the base64 and pasting that but it didn't work either)
Hostname: localhost or 127.0.0.1 (tried both)
Port: 1143
Authentication: Password
Allow insecure authentication: True
IMAP Path Prefix: empty
TLS Certificate: None
```

***

**SMTP**
```
Username: USERNAME (without @protonmail.com)
Password:   base64__32_byte_password= (I tried decoding the base64 and pasting that but it didn't work either)
Hostname: localhost or 127.0.0.1 (tried both)
Port: 1025
Authentication: Password or None (None connects but I can't send an email)
```

I fought for hours trying to make it work, I would appreciate some help. Once I figure it out I can write up a guide on how to set it up. Perhaps you can add it to the repo for other people to access.

Thank you for your help.

**Comment by emersion** [comment]
You're doing it right. The password is the base64-encoded string. Can you try to `netcat` into the IMAP server and authenticate by typing `001 LOGIN username password`?

I've just checked with single password and two password mode, and it works for me™.

**Comment by underthecocotree** [comment]
I managed to sort it out on thunderbird.

I noticed two things about my installation.
- I had not installed the GOPATH and GOROOT
- I was running hydroxide from my `~/` directory, which saved `auth.json` in my home directory, I don't know if that makes any difference. I am running the command from the `bin/` directory now (So I have no idea if it was not reading the auth.json file properly)

Mail.app seems to have a [bug](https://discussions.apple.com/thread/8087473?start=0&tstart=0) which doesn't save the `Allow insecure authentication` setting. So I think the minute I try to connect  Mail.app blocks the request because it's insecure.

**Comment by emersion** [comment]
Ah, this `auth.json` should be documented - and stored at a fixed location by default maybe?

TLS should also be supported.

**Comment by underthecocotree** [comment]
TLS would be great, I understand that might take a while.

About auth.json
If it is at the Readme file then people should be able to see what needs to be done and act accordingly.

If the file can be added to relation of where hydroxide resides, I guess it would work and read it from there. Some people might have different installations so how do you make sure it is always written where it is accessible?

I am not sure if the `auth.json` is read by imap and smtp. If they are, the best thing would be to exit and print a message. Something along the lines of `auth.json file not found`

My limited understanding is that auth.json is read by [/auth/auth.go](https://github.com/emersion/hydroxide/blob/ab599a27faa096da8af85a2bf6731b1ed652bf78/auth/auth.go#L28)
```
func readCachedAuths() (map[string]string, error) {
	f, err := os.Open(authFile)
	if os.IsNotExist(err) {

                // print auth.json file not found and exit?

		return nil, nil
	} else if err != nil {

               // print out error

		return nil, err
	}
	defer f.Close()
```

PS: I am not familiar with Go at all

**Comment by hkujari** [comment]
About Protonmail Bridge (Mac 10.15.7) and the freshest Bridge. Never have been able to make B work as long as it have been around. Three passwords (2 for browser based site and one from Bridge). Nothing works. All imaginable combinations and permutations tried. I have removed p-mail account from my Apple Mail, removed account from System preferences, re-installed it &c. Any ideas? —Harry Kujari
PS: From the view of the Bridge App I am »Connected» (**it seems to be in** with correct credentials).

**Comment by emersion** [comment]
@hkujari: this repo isn't about the official ProtonMail bridge.
