### ISSUE TITLE
Cannot log in to Proton Mail in Thunderbird with Hydroxide running as a service

### ISSUE THREAD

**Issue by dodo-the-dev** [emersion/hydroxide#263]
I have run the set up as per the readme and followed the guidance on one of the issues for people not being able to log in to Proton using their full username (use the first bit before @ first) #253 and that worked great.

The only downside was that I had to open a terminal window and run `hydroxide serve` before I could download my email. So I tried to run the hydroxide.service using Systemd and it ran fine, but when I then try and log in using Thunderbird, it said the password was incorrect. I ran `hydroxide auth [username]` again, got a new bridge password and put that in Thunderbird, but it wasn't having it.

I tried uninstalling Hydroxide and re-installing it (from AUR) and when I ran `hydroxide status` I was already logged in without having to log in again after a clean install (I'm guessing there's a file somewhere that holds all my details that wasn't deleted when I removed it using `yay -Rs hydroxide`).
If I disable the service and run `hydroxide serve` it works fine, it's like the hydroxide.service isn't pointing to the same authentication file created by manually running `hydroxide serve`.

Is there a way to point the hydroxide.service to the same auth file, or have I done something wrong?

Thanks and apologies in advance

**Comment by ma-04** [comment]
Normal systemd runs as root, while manually running hydroxide as normal user would put the files in user home.
so you if you want Normal systemd to access your already authenticated users, either run systemd as user with --user flag (put systemd service in user directory) or move/link your current user hydroxide files to root

**Comment by dodo-the-dev** [comment]
Well, I think that's the quickest resolustion I've ever had to an issue in Git Hub 🤣 

Thank you so much, that resolved the issue, sorry if it seemed a completely newb question, but TIL
