### ISSUE TITLE
Support multiple email addresses

### ISSUE THREAD

**Issue by underthecocotree** [emersion/hydroxide#27]
Protonmail Plus and on allow you to have multiple email accounts under one account. As far as I know it is to be used with your own domain.

eg. username@protonmail.com and username@companyname.com

Is this currently supported by hydroxide? From Thunderbird I can see that openpgp does not read the rest of the keys to decrypt the message.

Although I can see the list of messages when I try to open a message from a different email eg username@companyname.com then I get the following error: `The current operation on Inbox did not succeeded. The mail server for account username@protonmail.com responded: openpgp: incorrect key.`

I think each email has it's own key pair.

**Comment by emersion** [comment]
>I think each email has it's own key pair.

Correct. This is not yet supported, this is a TODO.

**Comment by emersion** [comment]
Fixed in https://github.com/emersion/hydroxide/pull/40

**Comment by typoworx-de** [comment]
Where are the keys stored can I make them persistent running hydroxide in docker-stack?
