### ISSUE TITLE
My accounts are suspended

### ISSUE THREAD

**Issue by nxjosephofficial** [emersion/hydroxide#276]
![image](https://github.com/user-attachments/assets/d4bc121d-3698-4084-a38a-a15832ce7fe8)
![image](https://github.com/user-attachments/assets/a8290a52-c2e2-413e-8598-8458e38a7021)

**Comment by emersion** [comment]
Nothing hydroxide can do about this.

**Comment by nxjosephofficial** [comment]
Sorry but I think you should write it down in README if mail accounts of people could be suspended in use of hydroxide.

**Comment by emersion** [comment]
First time hearing about such a case. I don't believe this is linked to hydroxide usage.

**Comment by nxjosephofficial** [comment]
I wonder if this is caused by me doing a lot `hydroxide auth`s (not repeated at a time). I don't know if there is a way to quit obsolete hydroxide sessions.

**Comment by nxjosephofficial** [comment]
I got my accounts back, they said their system blocked my accounts because of bulk registration.
