### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by apiote** [emersion/hydroxide#28]
I’ve just noticed that `hydroxide auth` results in error:

```
./hydroxide auth {here goes username}   
Password: {here goes hidden password}
2018/03/03 17:59:34 invalid character '<' looking for beginning of value
```

Instead of the error Hydroxide should ask for 2fa code.

**Comment by emersion** [comment]
Can you retry? It looks like a temporary ProtonMail failure.

**Comment by apiote** [comment]
Yeah… too soon. Works again. Sorry to bother.
