### ISSUE TITLE
Can't connect to Thunderbird with Hydroxide as a service

### ISSUE THREAD

**Issue by byjove01** [emersion/hydroxide#281]
I need to browse my mails frequently, so that I installed Hydroxide as a service.
I created a soft link between `/root/.config/hydroxide/auth.json` and `~/.config/hydroxide/auth.json` in order to synchronize logins. Then I followed the ReadMe and gave my authentification infos to Hydroxide, including the TOTP, before setting up in the server config correct values for ports, Connection security to "None" and removing the `@protonmail.com` part of the mail address. Before you ask, I obviously did put the bridge password into the e-mail password field instead of my mail provider's one, always before the TOTP code expires (how frustrating it is).

But even dozens of various attempts didn't allow me to connect that damn Thunderbird to Hydroxide.
Each time, I get either the "Unable to login at server" error or the "Incoming server already exists" one, that generally happens when I try to use the "manual configuration" button to create the account and set up the password then.

I'm sick of wasting my time, so I plead for your help.

**Comment by Renner0E** [comment]
Does it look like this?
![Screenshot-20241016_173257](https://github.com/user-attachments/assets/09c18e46-518d-4a9a-b159-fb54c8ec0fa1)

Are the necessary ports open?
`sudo netstat -tuplen | grep "1143\|1025\|8080"`

**Comment by byjove01** [comment]
1) Yes !
2) They are. Anyways, Hydroxide didn't output any error related to ports status.
`tcp        0      0 127.0.0.1:1025          0.0.0.0:*               LISTEN      941        10178      737/hydroxide
tcp        0      0 127.0.0.1:1143          0.0.0.0:*               LISTEN      941        14018      737/hydroxide
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      941        11641      737/hydroxide`

**Comment by Renner0E** [comment]
Whats the output of `journalctl --since=today | grep hydroxide` anything remarkable?

What does `ls -lah ~/.config/hydroxide` say?

Btw I made a Container Image with Instructions for Noobies on my gitlab with podman.
You just need to install podman.

https://gitlab.com/Renner0E/hydroxide-podman

**Comment by byjove01** [comment]
`journalctl --since=today | grep hydroxide`
```
oct. 16 08:03:28 pchost-1 hydroxide[737]: 2024/10/16 08:03:28 CardDAV server listening on 127.0.0.1:8080
oct. 16 08:03:28 pchost-1 hydroxide[737]: 2024/10/16 08:03:28 IMAP server listening on 127.0.0.1:1143
oct. 16 08:03:28 pchost-1 hydroxide[737]: 2024/10/16 08:03:28 SMTP server listening on 127.0.0.1:1025

```
` ls -lah ~/.config/hydroxide `
`-rw-r--r--   1 byjove byjove 1,4K 15 oct.  14:02 auth.json`

**Comment by Renner0E** [comment]
Distro?
> I installed Hydroxide as a service.

Post the Systemd Service file please

sudo systemctl status hydroxide ?

**Comment by byjove01** [comment]
Arch Linux.

```
[Unit]
Description=A third-party, open-source ProtonMail CardDAV, IMAP and SMTP bridge
Wants=network.service

[Service]
User=hydroxide
Environment=XDG_CONFIG_HOME=/etc
ExecStart=/usr/bin/hydroxide serve
Restart=always

[Install]
WantedBy=multi-user.target
```

```
● hydroxide.service - A third-party, open-source ProtonMail CardDAV, IMAP and SMTP bridge
Loaded: loaded (/usr/lib/systemd/system/hydroxide.service; enabled; preset: disabled)
Active: active (running) since Wed 2024-10-16 08:03:28 CEST; 12h ago
Invocation: be7f4e993dd54388850c2503fae52f70
Main PID: 737 (hydroxide)
Tasks: 7 (limit: 18948)
Memory: 13.6M (peak: 14.1M)
CPU: 26ms
CGroup: /system.slice/hydroxide.service
└─737 /usr/bin/hydroxide serve

oct. 16 08:03:28 pchost-1 systemd[1]: Started A third-party, open-source ProtonMail CardDAV, IMAP and SMTP bridge.
oct. 16 08:03:28 pchost-1 hydroxide[737]: 2024/10/16 08:03:28 CardDAV server listening on 127.0.0.1:8080
oct. 16 08:03:28 pchost-1 hydroxide[737]: 2024/10/16 08:03:28 IMAP server listening on 127.0.0.1:1143
oct. 16 08:03:28 pchost-1 hydroxide[737]: 2024/10/16 08:03:28 SMTP server listening on 127.0.0.1:1025
```

**Comment by Renner0E** [comment]
How did you make the symlink?
Why not just run in as your regular user account?

Does it work if you manually run` hydroxide serve`. kill the hydroxide process first/ stop systemd service, if you have to.

`XDG_CONFIG_HOME is set to /etc`

Can you `ls -lah`  in `/etc/hydroxide and /root/hydroxide` ?

**Comment by Renner0E** [comment]
Is it actually config and not ~/.config?

**Comment by byjove01** [comment]
Yes, typo, my bad.

**Comment by Renner0E** [comment]
Wait I just noticed the AUR package has a service that runs as the hydroxide user. Does the hydroxide user have a home dir? Can you `sudo su hydroxide`
If that is the case you may have to run `hydroxide auth` as the hydroxide user.

I think you don't have to symlink anything.
That would defeat the entire purpose of having a separate user.

If that doesn't work. I'd just nuke every hydroxide config directory.

Don't run anything from the readme.

Please try the user service: https://aur.archlinux.org/cgit/aur.git/tree/user.service?h=hydroxide

If all else fails, consult the AUR comments. This is an issue with the AUR Package I believe.
