### ISSUE TITLE
Update ReadMe with status of Android SMTP/IMAP compatibility?

### ISSUE THREAD

**Issue by e-t-l** [emersion/hydroxide#286]
What is the status of Hydroxide's stability running on Android (e.g. in Termux) in 2024? The only mention of Android is that carddav works, but several issues here allude to varying levels of success on Android (possibly dependent on mail client choice?)

Relatedly, the readme doesn't really give much useful info on the stability of IMAP in general. "Here be dragons," really? Given that *receiving email* is kind of a core feature for email clients, it would be good to know whether IMAP is 1) generally stable with specific limitations, 2) intermittently unstable, or 3) generally unstable/unsuitable for a daily driver.

**Comment by WuShufei** [comment]
The SMTP-only (unfortunately) makes sense if one views this as a provision for spammers to use Proton.  I certainly second the request for more clarity on IMAP.

**Comment by emersion** [comment]
I haven't tried running on Android so can't say. I wouldn't recommend using IMAP, might mix up emails. I will note that I don't really appreciate the tone used here: if you need this "core feature", please just ignore hydroxide and move on.

> The SMTP-only (unfortunately) makes sense if one views this as a provision for spammers to use Proton.

Great. I personally use hydroxide for git-send-email, FWIW. Again, if you don't see a use-cases besides spamming, nobody is forcing you to use hydroxide.
