### ISSUE TITLE
Document how to use/install

### ISSUE THREAD

**Issue by v01d** [emersion/hydroxide#29]
Hi, just found this and I'm really interested in it. However, I don't really understand how it works (I know it talks to protonmail's using its API). For example, does it retrieve the private key on its own from the server? The password for the key (the one used for login) is the password that should be used for the auth command?
I would like also to understand how is the sensitive data stored (key, password, decrypted emails, etc).

**Comment by emersion** [comment]
Yeah, hydroxide is missing some docs.

>does it retrieve the private key on its own from the server?

Yeah.

>The password for the key (the one used for login) is the password that should be used for the auth command?

Yes. Just login with hydroxide just like you would auth with ProtonMail's website.

>I would like also to understand how is the sensitive data stored (key, password, decrypted emails, etc).

The key is stored in memory, not on disk. The password is stored encrypted on disk (encrypted with the random client password printed after you run `hydroxide auth`). Decrypted emails are not stored (but your email client probably stores them unencrypted on disk).

**Comment by v01d** [comment]
Cool, thank you for your answers. 
What about two-password mode? Is it supported?
Also, what is the general status of the bridge? I mean, are there particularly important features that are not yet implemented? Is it mostly stable?

**Comment by v01d** [comment]
Also, does this bridge also require a paid account or the API access is free?

**Comment by emersion** [comment]
>What about two-password mode? Is it supported?

Yes.

>Also, what is the general status of the bridge? I mean, are there particularly important features that are not yet implemented? Is it mostly stable?

It's not stable, it needs more testing and it has missing features. The SMTP and CardDAV backends work pretty well though.
