### ISSUE TITLE
request failed: POST https://mail.proton.me/api/messages: [2001] Invalid sender

### ISSUE THREAD

**Issue by FullMetalJew** [emersion/hydroxide#294]
Reletively new to linux and using hydroxide so please forgive me. 

I set everything up, and it logs in and downloads emails but sending is another story.... here is the log.

```
Dec 17 05:49:12 nobara-pc hydroxide[31636]: 2024/12/17 05:49:12 User "J.Sinofsky" logged in via IMAP
Dec 17 05:49:12 nobara-pc hydroxide[31636]: 2024/12/17 05:49:12 Synchronizing mailbox INBOX...
Dec 17 05:49:15 nobara-pc hydroxide[31636]: 2024/12/17 05:49:15 Synchronizing mailbox INBOX: done.
Dec 17 05:50:04 nobara-pc hydroxide[31636]: 2024/12/17 05:50:04 j.sinofsky@protonmail.com logged in
Dec 17 05:52:30 nobara-pc hydroxide[31636]: 2024/12/17 05:52:30 User "J.Sinofsky" logged out via IMAP
Dec 17 05:52:35 nobara-pc hydroxide[31636]: 2024/12/17 05:52:35 User "J.Sinofsky" logged in via IMAP
Dec 17 05:52:36 nobara-pc hydroxide[31636]: 2024/12/17 05:52:36 Synchronizing mailbox INBOX...
Dec 17 05:52:39 nobara-pc hydroxide[31636]: 2024/12/17 05:52:39 Synchronizing mailbox INBOX: done.
Dec 17 05:57:54 nobara-pc hydroxide[31636]: 2024/12/17 05:57:54 j.sinofsky@protonmail.com logged in
Dec 17 05:57:54 nobara-pc hydroxide[31636]: 2024/12/17 05:57:54 creating draft message
Dec 17 05:57:54 nobara-pc hydroxide[31636]: 2024/12/17 05:57:54 request failed: POST https://mail.proton.me/api/messages: [2001] Invalid sender
```

Ive gone ahead and reinstalled all the latest software, thunderbird, hydroxide, and removed and resinstalled it multiple times.   Not sure what else to do. Atleast i can still get email.

**Comment by ajkessel** [comment]
Are you setting a custom from address in Thunderbird? The Proton API will only accept mail “from” your actual Protonmail address or an alias configured within Protonmail.

**Comment by FullMetalJew** [comment]
Hey @ajkessel  firstly I would like to thank you for your response, it's always nice to know im not alone in troubleshooting. 

I will say, im not sure if Thunderbird by default is attempting to set a custom address, so the best i can do to answer this in my mind is provide screen shots.  Sorry for the inconvience. Please assume that I am 7 years old. (Im not...)

![image](https://github.com/user-attachments/assets/b55c06b2-bbe7-4fc5-82fe-e065fcdd32ea)

**Comment by FullMetalJew** [comment]
In response to your inquery here.

![image](https://github.com/user-attachments/assets/0c7b0321-786c-4790-907b-41b0fc9d3f98)

**Comment by ajkessel** [comment]
Oh, try dropping the domain name from your username. I believe that's how I had it configured when it worked for me.

**Comment by FullMetalJew** [comment]
So something like J.sinofsky?

**Comment by ajkessel** [comment]
Yeah, see if username `j.sinofsky` works.

**Comment by FullMetalJew** [comment]
It did not, but What did was changing it to J.Sinofsky@protonmail.com as opposed to j.sinofsky@protonmail.com  it seems the smtp is CASE SENSITIVE

**Comment by ajkessel** [comment]
That's weird, since email addresses are not, in fact, case sensitive. But apparently this is a server-side issue that we can't control.
