### ISSUE TITLE
settings for servers

### ISSUE THREAD

**Issue by foot-gloves** [emersion/hydroxide#35]
I'm not sure if I missed this in any of the documentation but is there a way to run the imap/smtp servers with custom settings for listen interface and port?

So far I've just been building my own version locally after editing the "port" and "addr" variables in hydroxide.go

**Comment by emersion** [comment]
You can override the port by setting the `PORT` env variable. This is not ideal, it would be better to add a `-addr` flag. Pull requests welcome!

**Comment by foot-gloves** [comment]
Thanks for the info! I'll take a look at implementing the flag. I have some other ideas so I might do them all at once.

**Comment by emersion** [comment]
Fixed in https://github.com/emersion/hydroxide/pull/66
