### ISSUE TITLE
ProtonMail requires new version

### ISSUE THREAD

**Issue by apiote** [emersion/hydroxide#36]
Hydroxide reports
`2018/10/16 19:45:56 [5003] Update required: Please refresh the page to load the latest version of the application`
upon login.

**Comment by emersion** [comment]
Thanks for the report. Can you extract the new version from the browser inspector while using the webapp and update it here: https://github.com/emersion/hydroxide/blob/master/cmd/hydroxide/hydroxide.go#L28

**Comment by apiote** [comment]
Yes. Did so — Web_3.14.19 works perfectly.

**Comment by emersion** [comment]
Excellent. Could you open a pull request?

**Comment by apiote** [comment]
done: #37
