### ISSUE TITLE
How to build your go project in a sandboxed manner?

### ISSUE THREAD

**Issue by cookiengineer** [emersion/hydroxide#42]
Hello,

I'm maintaining the arch linux / AUR package for [hydroxide-git](https://aur.archlinux.org/packages/hydroxide-git/) package and so far I was able to build it using these instructions inside a chroot:

```bash
build() {
	GOPATH="$srcdir" go get -fix -v -x ${_gourl}/cmd/hydroxide
}

check() {
	GOPATH="$GOPATH:$srcdir" go test -v -x ${_gourl}/cmd/hydroxide
}

package() {

	mkdir -p "$pkgdir/usr/bin"
	install -p -m755 "$srcdir/bin/"* "$pkgdir/usr/bin"

	mkdir -p "$pkgdir/usr/lib/go"
	cp -Rv --preserve=timestamps "$srcdir/src" "$pkgdir/usr/lib/go"

	install -Dm644 "$srcdir/src/$_gourl/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"

}
```

Since your last updates (around 2 weeks ago) I'm trying to figure out how to build hydroxide in this sandboxed manner, but I'm unable to understand WTF is going on behind the scenes.

I do not want to pollute the user's machine. Which means both `GOROOT` and `GOPATH` have to be inside the chroot, and NOT a global one. That's indiscussable and is a fixed requirement.

Now the PKGBUILD file looks like this:

```bash
build() {
	export GOPATH="$srcdir/gopath";
	export GOROOT="$srcdir/goroot";

	cd "$srcdir";
	go get -v -x ${_gourl}/cmd/hydroxide;

}

check() {

	export GOPATH="$srcdir/gopath";
	export GOROOT="$srcdir/goroot";

	cd "$srcdir";
	go test -v -x ${_gourl}/cmd/hydroxide;

}
```

When I set the GOPATH and GOROOT I will end up with "import path does not begin with hostname" errors everywhere now. Literally, thousands of packages in the dependency tree seem to use the legacy syntax before go 1.7. Google Fu returns only automated build pipeline errors, and not a single explanation on how the problem came to be and how to solve it. People always say "just unset your GOPATH or GOROOT, and it will work" - which I cannot do because of the chroot.

So, my questions are now something like this:

- Why can't I do something like `git clone hydroxide ./somewhere; cd ./somewhere; go build;`?
- Do I have to use `go get`? I want to avoid it, because go get is too stupid for a package cache, and will always pollute stuff outside the goroot, in multiple ways. And it seems that go get also is too stupid to resolve the namespace of the package it is currently building; with no instructions searchable on how to fix that either.
- How to build `hydroxide` without using `go get`?

PS: Please, bear with me, I'm not a go developer, so I am just trying to get shit to run; and assume that I'm a noob level zero.

**Comment by emersion** [comment]
>Why can't I do something like git clone hydroxide ./somewhere; cd ./somewhere; go build;?

This is how you do it with Go 1.11. It should work if you clone outside GOPATH (which is always the case for PKGBUILD), try it.

**Comment by cookiengineer** [comment]
This is what I tried at first, but then it couldn't find the module that provides hydroxide itself.

Error was/is then:

```
can't load package: package github.com/emersion/hydroxide: unknown import path "github.com/emersion/hydroxide": cannot find module providing package github.com/emersion/hydroxide
```

... and I was trying to execute `go build` inside the repo's root folder (same folder wherein the `go.mod` file is located). If I use `go build`, do I need to set some environment variables or special flags, so that go finds the `go.mod` file?

**Comment by cookiengineer** [comment]
Okay, for future references (in case somebody has the same problem):

- `go build` will only check the local `go.mod` file if a build target is given, which means `cd ./hydroxide; go build ./cmd/hydroxide` is necessary. Paths to `.go` files doesn't work.
- This behaviour is only the case when `GOPATH` and `GOROOT` both are _unset_. If they are set, it behaves differently.

So all in all, the new PKGBUILD file for `hydroxide-git` looks super simple, like this (go version `1.11` and later):

```bash
pkgname=hydroxide-git
pkgver=r1.05d0806
pkgrel=1
pkgdesc="A third-party, open-source ProtonMail CardDAV, IMAP and SMTP bridge"
arch=('x86_64')
makedepends=('git' 'go')
url="https://github.com/emersion/hydroxide"
license=('MIT')
source=('git+https://github.com/emersion/hydroxide')
md5sums=('SKIP')

pkgver() {
	cd "$srcdir/hydroxide"
	printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

build() {
	cd "$srcdir/hydroxide";
	go build "./cmd/hydroxide";
}

package() {
	mkdir -p "$pkgdir/usr/bin"
	install -p -m755 "$srcdir/hydroxide/hydroxide" "$pkgdir/usr/bin"
	install -Dm644 "$srcdir/hydroxide/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
```

@emersion Sorry for the trouble, thanks for the help! Your comment led me on the right path.

**Comment by emersion** [comment]
>This behaviour is only the case when GOPATH and GOROOT both are unset. If they are set, it behaves differently.

Hmm, I have GOPATH and GOROOT set and `go build ./cmd/hydroxide` works. Only works if I cloned outside GOPATH though.

Anyway, nice you've figured it out!
