### ISSUE TITLE
Auth error: "failed to unlock key [key]. openpgp: invalid data: private key checksum failure

### ISSUE THREAD

**Issue by d4hines** [emersion/hydroxide#43]
Hello,
I'm seeing from #29 that I should use my normal ProtonMail password when trying to set up credentials with `hydroxide auth`. However, I get this error every time:
```bash
./hydroxide auth [username]
Password:
2018/11/24 10:27:41 failed to unlock key [key]: openpgp: invalid data: private key checksum failure
Bridge password: rBLy+TpeewzrvoEN+jJie0Yh9409IHPDauvSF0AsbRM=
```
Am I doing something wrong?
Thanks,
Daniel Hines

**Comment by emersion** [comment]
This is just a warning, it happens when you have an old key with different password you don't remember. See "Keys" in your ProtonMail settings.

Updated the error message in https://github.com/emersion/hydroxide/commit/ee861e4175f50fe941b1a0624a130dac99fe3aa9 to make it clear it's not fatal.
