### ISSUE TITLE
Error on build: undefined: smtp.User

### ISSUE THREAD

**Issue by nast90210** [emersion/hydroxide#50]
Hi all! I get an error when build hydroxide from the source:
go/src/github.com/emersion/hydroxide/smtp/smtp.go:352:54: undefined: smtp.User
go/src/github.com/emersion/hydroxide/smtp/smtp.go:373:38: undefined: smtp.User

I'm not good in Go, but it seems that instead of smtp.User smtp.Backend must be used?

**Comment by emersion** [comment]
It seems you're trying to use the latest version of go-smtp. hydroxide has not yet been updated for that. Instead, the go-smtp version to use is recorded in https://github.com/emersion/hydroxide/blob/master/go.mod

Do you have a recent version of Go?

Can you try cloning the repo and running `go build` inside?

**Comment by nast90210** [comment]
Well, as I mention above - I'm not good in Go))
I try to build by - go get github.com/emersion/hydroxide/cmd/hydroxide and get that error.

go version go1.12.1 darwin/amd64

Yeap - I download .zip and successfully build by go build.
Thank you for help!

**Comment by kprasadvnsi** [comment]
I am having the same problem but unable to solve it. @nast90210  can you explain how you compile it?

**Comment by nast90210** [comment]
Yeap - I download .zip, go to emersion/hydroxide/cmd/hydroxide folder and run command: go build

**Comment by emersion** [comment]
Fixed in 8f16741
