### ISSUE TITLE
High CPU usage by hydroxide imap when offline

### ISSUE THREAD

**Issue by dvalter** [emersion/hydroxide#56]
When no connection to Protonmail is available (e.g. computer wakes up without Internet connection), hydroxide may start doing the following queries a few thousand times a second:
`hydroxide[1325]: 2019/05/23 14:37:41 cannot receive event: Get https://dev.protonmail.com/api/events/u<...>A==: dial tcp: lookup dev.protonmail.com: Temporary failure in name resolution`

Some sort of timeout (probably progressive) may fix this.

**Comment by emersion** [comment]
Hmm. Indeed, that seems like a good idea.
