### ISSUE TITLE
'hydroxide serve' doesn't work

### ISSUE THREAD

**Issue by tichli** [emersion/hydroxide#61]
Hi there,
Here is what I obtain with 'serve' or 'server', any idea ?

max@machine:~$ hydroxide serve
2019/07/18 22:20:35 usage: hydroxide carddav
2019/07/18 22:20:35 usage: hydroxide smtp
2019/07/18 22:20:35 usage: hydroxide auth <username>
2019/07/18 22:20:35 usage: hydroxide export-secret-keys <username>
2019/07/18 22:20:35 usage: hydroxide status
2019/07/18 22:20:35 Unrecognized command

**Comment by emersion** [comment]
Maybe you have an outdated `hydroxide`?

**Comment by tichli** [comment]
> Maybe you have an outdated `hydroxide`?

I have just installed it using 'GO111MODULE=on go get github.com/emersion/hydroxide/cmd/hydroxide'

**Comment by emersion** [comment]
Just released a new version. Can you try again?

**Comment by tichli** [comment]
> Just released a new version. Can you try again?

All good :) Thank you for the good work
