### ISSUE TITLE
Complains about some "Update required"

### ISSUE THREAD

**Issue by icyphox** [emersion/hydroxide#62]
Anything I attempt returns this output:

```
2019/07/24 22:29:13 [5003] Update required: Please refresh the page to load the latest version of the application
```

**Comment by emersion** [comment]
[`AppVersion`](https://github.com/emersion/hydroxide/blob/master/cmd/hydroxide/hydroxide.go#L31) needs to be updated with the webmail's. It's sent by all webmail requests.

**Comment by icyphox** [comment]
Ah right. I've made the fix locally for now, I'll wait for you to push the new one.

**Comment by emersion** [comment]
Can you send a PR?

**Comment by icyphox** [comment]
Sure, gimme a bit.
