### ISSUE TITLE
failed to read auth key ring: openpgp: invalid argument: no armored data found

### ISSUE THREAD

**Issue by chebyte** [emersion/hydroxide#67]
hello there,I cant make auth, I get the following error

````
./hydroxide auth xxxx
Password:
2019/08/05 17:48:55 warning: failed to check SRP modulus signature: openpgp: unsupported feature: public key algorithm 22
2019/08/05 17:48:56 failed to read auth key ring: openpgp: invalid argument: no armored data found
````

thanks!

**Comment by chebyte** [comment]
it was working but after many tries, is returning this error, I was logging more and seems that the private key is empty

````
	keyRing, err := openpgp.ReadArmoredKeyRing(strings.NewReader(auth.privateKey))
	if err != nil {
		return nil, fmt.Errorf("failed to read auth key ring: %v", err)
	}

````

but `auth.privateKey` is empty, 

any idea?

**Comment by lambdatronic** [comment]
I'm getting the same error this morning when I try to connect to hydroxide through offlineimap. This was working just fine for the past week or so, but now it's dead in the water.

Account sync protonmail:
 LOGIN authentication failed: failed to read auth key ring: openpgp: invalid argument: no armored data found
 ERROR: All authentication types failed:
	PLAIN: failed to read auth key ring: openpgp: invalid argument: no armored data found
	LOGIN: failed to read auth key ring: openpgp: invalid argument: no armored data found

**Comment by chebyte** [comment]
yeap seems that proton change something, I cant login with any of two proton paid account that I have

seems that it is URGENT!

**Comment by chebyte** [comment]
the problem is that privateKey is returning empty when hydroxide send the authentication params

**Comment by emersion** [comment]
This commit seems to be the culprit: https://github.com/ProtonMail/WebClient/commit/970344c25b03613c646adf2414229a839ad04e5d

**Comment by emersion** [comment]
>seems that it is URGENT!

Note that I've fixed this particular issue, but in general I don't provide any guarantee that I'll fix any bug at all.
