### ISSUE TITLE
Token insufficient scope

### ISSUE THREAD

**Issue by hughwilliams94** [emersion/hydroxide#68]
Trying to send messages via msmtp with the command `echo -e "Subject: Test Mail\r\n\r\nThis is a test mail" | msmtp --tls=off --auth=plain --debug -a proton XXX@XXX.X` fails with the following message:

```
msmtp: authentication failed (method PLAIN
msmtp: server message: 454 4.7.0 [403] Access token does not have sufficient scope
```

I have tried reauthorizing with PM but to no avail. Is there anything else I can provide to help debug?

**Comment by emersion** [comment]
I had the same issue. Restarting hydroxide helped.

**Comment by hughwilliams94** [comment]
Ahh will try this

**Comment by hughwilliams94** [comment]
I am now getting this:

```
<-- 454 4.7.0 cannot re-authenticate: two factor authentication enabled, please login manually
msmtp: authentication failed (method PLAIN)
msmtp: server message: 454 4.7.0 cannot re-authenticate: two factor authentication enabled, please login manually
```
If I restart hydroxide, do I need to reauth as well?

**Comment by emersion** [comment]
Hmm, it seems the server is saying our access token is expired. Weird.

Can you try stopping hydroxide, re-authenticating, and starting hydroxide again?

**Comment by hughwilliams94** [comment]
It just goes back to this error:

```
<-- 454 4.7.0 [403] Access token does not have sufficient scope
msmtp: authentication failed (method PLAIN)
msmtp: server message: 454 4.7.0 [403] Access token does not have sufficient scope
```

**Comment by emersion** [comment]
Bleh. I haven't tested 2FA for a while, maybe that's broken.

**Comment by hughwilliams94** [comment]
Well let me know if there is anymore info I can provide. Sorry that I can't be of any more help than that.

**Comment by emersion** [comment]
Bleh, still not fixed. I thought it was fixed because I tried twice in a row and the server replied with "invalid refresh token" (making hydroxide re-authenticate) instead of this scope error.
