### ISSUE TITLE
Issue with smtp; related to refreshing auth tokens?

### ISSUE THREAD

**Issue by reedriley** [emersion/hydroxide#70]
I just tried to set up Hydroxide to use as an SMTP proxy; but I'm hitting some kind of error.

`hydroxide auth <username>` works and initializes things as I'd expect; and my SMTP client is connecting properly.

I see the following error when the SMTP client tries to send an email:
```
smtp: Failed: 454 4.7.0 [2000] Invalid input
Sending failed: Temporary error in sending the message
```

When I look at the console output from `hydroxide smtp`, I see the following corresponding error:
```
2019/09/27 03:03:21 request failed: POST https://mail.protonmail.com/api/auth/refresh: [2000] Invalid input
```

My best guess is that something has changed about the `https://mail.protonmail.com/api/auth/refresh` API which is breaking things?

**Comment by fancycade** [comment]
Facing similar issue.

**Comment by dvalter** [comment]
The same issue with IMAP.

I don't know, what actually causes this issue (except the fact that I could not find any mention of refresh in Protonmail JS code), but the following patch "fixes" the issue by using password when refresh has failed with 2000
```diff
diff --git a/auth/auth.go b/auth/auth.go
index bf6c568..ebae80d 100644
--- a/auth/auth.go
+++ b/auth/auth.go
@@ -112,7 +112,7 @@ func EncryptAndSave(auth *CachedAuth, username string, secretKey *[32]byte) erro
 
 func authenticate(c *protonmail.Client, cachedAuth *CachedAuth, username string) (openpgp.EntityList, error) {
        auth, err := c.AuthRefresh(&cachedAuth.Auth)
-       if apiErr, ok := err.(*protonmail.APIError); ok && apiErr.Code == 10013 {
+       if apiErr, ok := err.(*protonmail.APIError); (ok && apiErr.Code == 10013) || (apiErr.Code == 2000) {
                // Invalid refresh token, re-authenticate
                authInfo, err := c.AuthInfo(username)
                if err != nil {
```

**Comment by bicarus** [comment]
The same issue here. Hope to fix. Thanks

**Comment by emersion** [comment]
Landed the workaround in 0.v0.2.10. Please keep this issue opened until we find a better solution.

**Comment by emersion** [comment]
If someone has time to investigate, here are some iOS code excerpts:

- https://github.com/ProtonMail/ios-mail/blob/28de7e27ca39d4df9144818c4dd5eca939cd290f/ProtonMail/ProtonMailCommon/DataServices/APIService/AuthAPI.swift#L210
- https://github.com/ProtonMail/ios-mail/blob/28de7e27ca39d4df9144818c4dd5eca939cd290f/ProtonMail/ProtonMailCommon/Network/APIService%2BAuthenticationExtension.swift#L222
- https://github.com/ProtonMail/ios-mail/blob/28de7e27ca39d4df9144818c4dd5eca939cd290f/ProtonMail/ProtonMailCommon/Network/APIService.swift#L138

**Comment by emersion** [comment]
Hmm, I managed to make it work on my account: https://github.com/emersion/hydroxide/commit/db983eed89105b4d93f68cf9732fdcd4fe288b56

Can someone else try this patch and confirm it works there too?

**Comment by bicarus** [comment]
![image](https://user-images.githubusercontent.com/12370387/68930365-2f345080-07c9-11ea-80ac-0f78adb8d01e.png)
Thanks for your work! I have tested it . It works perfectly!

**Comment by snex** [comment]
After upgrading to 0.2.28, I am getting this error.
