### ISSUE TITLE
new error on auth

### ISSUE THREAD

**Issue by sammyf** [emersion/hydroxide#75]
with a completely fresh (incl. all dependencies) build of hydroxide I get the following error message when I try to AUTHenticate

```
$ ./hydroxide auth xxxxxx@protonmail.com
$ Password: 
2019/11/13 08:45:32 request failed: POST https://mail.protonmail.com/api/auth/info: [5003] Update required: Please refresh the page to load the latest version of the application
2019/11/13 08:45:32 [5003] Update required: Please refresh the page to load the latest version of the application
```

The account has 2FA via Authy enabled. Maybe that's the problem?

**Comment by emersion** [comment]
Please update your version of hydroxide. A fix has already landed in the master branch.
