### ISSUE TITLE
failed to unlock any key

### ISSUE THREAD

**Issue by eternal-sorrow** [emersion/hydroxide#77]
Just tried to auth, got this failure:
```
hydroxide auth <username>
Password:
2019/12/08 21:37:29 warning: failed to check SRP modulus signature: openpgp: unsupported feature: public key algorithm 22
2FA TOTP code: <code>
Mailbox password:
2019/12/08 21:38:02 warning: failed to unlock key "<username>@protonmail.ch" <KEY_ID>: openpgp: invalid data: private key checksum failure
2019/12/08 21:38:02 warning: failed to unlock key "<username>@protonmail.com" <KEY_ID>: openpgp: invalid data: private key checksum failure
2019/12/08 21:38:03 warning: failed to unlock key "<username>@pm.me" <KEY_ID>: openpgp: invalid data: private key checksum failure
2019/12/08 21:38:03 failed to unlock any key
```
... and no bridge password.

**Comment by eternal-sorrow** [comment]
My fail, either I used the wrong version of one of deps when built hydroxide or I just input wrong mailbox password.

**Comment by hakova** [comment]
I am having this same issue as of tonight on Nixos 21.11. The funny thing is that Protonmail logs show "Sign in success", however, no bridge password is printed on the screen, just the output original author posted except 2FA, which I don't have set up.

Thanks in advance for guidance.
