### ISSUE TITLE
imap error: auth/refresh Invalid refresh token

### ISSUE THREAD

**Issue by rajeevn1** [emersion/hydroxide#81]
request failed: POST https://mail.protonmail.com/api/auth/refresh: [10013] Invalid refresh token

**Comment by emersion** [comment]
Can you provide more details?

**Comment by rajeevn1** [comment]
Following the instructions, I got the bridge password, and started the bridge, but when I try to connect to the imap port using the bridge password, the connection fails and I see the above listed error in the bridge log.

Please let me know how can I provide more information.

**Comment by CakeMasterino** [comment]
I've ran into the same issue yesterday.
SMTP seems to work fine however.

**Comment by rajeevn1** [comment]
I had 2FA.  I disabled it, and the problem is resolved.

**Comment by Skirmisher** [comment]
Seeing the same issue. Running `hydroxide auth` seems to work normally, asking for my password and a 2FA code in turn, but subsequently running `hydroxide serve` and connecting with KMail gets me `Login failed, server replied: A000001 NO cannot re-authenticate: two factor authentication enabled, please login manually`. Same refresh token error in the hydroxide output.

Disabling 2FA is not a solution for me. Happy to assist in debugging.

**Comment by matt-snider** [comment]
I have the same issue with the same error message as reported by @rajeevn1. Also using 2FA and was able to run `hydroxide auth` without an issue.

I'm using the package from [nixpkgs](https://github.com/NixOS/nixpkgs/blob/2318f7fc44918b79b233eccd9a8edb72d26e5604/pkgs/applications/networking/hydroxide/default.nix) which could be relevant since it uses v2.11 with a patch for 2FA, but this is unlikely If the other users are using v2.12 and still having the issue.

@rajeevn1 @Skirmisher which package/distro/version are you using?

**Comment by rajeevn1** [comment]
I build the latest release from github using
    go get github.com/emersion/hydroxide/cmd/hydroxide
go version go1.13.5 linux/amd64

**Comment by Skirmisher** [comment]
Same here (including go version), followed the instructions in the readme to build from source, so I'm running 0.2.12 (though the program doesn't seem to display version info).

**Comment by emersion** [comment]
It seems like the refresh token doesn't work properly anymore.

**Comment by xcffl** [comment]
Perhaps you can use https://beta.protonmail.com/api/auth/cookies now

Response
````
{"Code":1000,"SessionToken":"****","UID":"****"}
````

**Comment by eternal-sorrow** [comment]
So? Is it going to be fixed sometime soon? Disabling 2fa is not an option

**Comment by emersion** [comment]
>Is it going to be fixed sometime soon?

Yes, if you send a patch.

**Comment by jsxof** [comment]
I have that problem too, although I don't use 2FA.

**Comment by eternal-sorrow** [comment]
Not fixed for me on 0.2.14

**Comment by emersion** [comment]
Please provide debug logs:

```
hydroxide -debug serve
```

Make sure to redact your tokens and passwords.

**Comment by eternal-sorrow** [comment]
```
2020/03/08 05:03:38 CardDAV server listening on 127.0.0.1:8080
2020/03/08 05:03:38 SMTP server listening on 127.0.0.1:1025
2020/03/08 05:03:38 IMAP server listening on 127.0.0.1:1143
* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR AUTH=PLAIN] IMAP4rev1 Service Ready
1 authenticate PLAIN
+
2020/03/08 05:03:44 >> POST /api/auth/refresh
2020/03/08 05:03:44 {"RefreshToken":"<token>","ResponseType":"token","GrantType":"refresh_token","RedirectURI":"http://www.protonmail.ch"}
2020/03/08 05:03:45 << POST /api/auth/refresh
2020/03/08 05:03:45 &protonmail.authResp{resp:protonmail.resp{Code:10013, RawAPIError:(*protonmail.RawAPIError)(0xc000256040)}, Auth:protonmail.Auth{ExpiresAt:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Scope:"", UID:"", AccessToken:"", RefreshToken:"", UserID:"", EventID:"", PasswordMode:0, TwoFactor:struct { Enabled int; U2F interface {}; TOTP int }{Enabled:0, U2F:interface {}(nil), TOTP:0}}, ExpiresIn:0, TokenType:"", ServerProof:""}
2020/03/08 05:03:45 request failed: POST https://mail.protonmail.com/api/auth/refresh: [10013] Invalid refresh token
2020/03/08 05:03:45 >> POST /api/auth/info
2020/03/08 05:03:45 {"Username":"<username>"}
2020/03/08 05:03:46 << POST /api/auth/info
2020/03/08 05:03:46 &protonmail.AuthInfoResp{resp:protonmail.resp{Code:1000, RawAPIError:(*protonmail.RawAPIError)(nil)}, AuthInfo:protonmail.AuthInfo{version:0, modulus:"", serverEphemeral:"", salt:"", srpSession:""}, Version:4, Modulus:"<pgp signed message with signature>", ServerEphemeral:"<base64 data>", Salt:"<salt>", SRPSession:"<data>"}
1 NO cannot re-authenticate: two factor authentication enabled, please login manually
3 login "<username>" "<password>"
2020/03/08 05:03:46 >> POST /api/auth/refresh
2020/03/08 05:03:46 {"RefreshToken":"<token>","ResponseType":"token","GrantType":"refresh_token","RedirectURI":"http://www.protonmail.ch"}
2020/03/08 05:03:46 << POST /api/auth/refresh
2020/03/08 05:03:46 &protonmail.authResp{resp:protonmail.resp{Code:10013, RawAPIError:(*protonmail.RawAPIError)(0xc000234fb0)}, Auth:protonmail.Auth{ExpiresAt:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Scope:"", UID:"", AccessToken:"", RefreshToken:"", UserID:"", EventID:"", PasswordMode:0, TwoFactor:struct { Enabled int; U2F interface {}; TOTP int }{Enabled:0, U2F:interface {}(nil), TOTP:0}}, ExpiresIn:0, TokenType:"", ServerProof:""}
2020/03/08 05:03:46 request failed: POST https://mail.protonmail.com/api/auth/refresh: [10013] Invalid refresh token
2020/03/08 05:03:46 >> POST /api/auth/info
2020/03/08 05:03:46 {"Username":"<username>"}
2020/03/08 05:03:46 << POST /api/auth/info
2020/03/08 05:03:46 &protonmail.AuthInfoResp{resp:protonmail.resp{Code:1000, RawAPIError:(*protonmail.RawAPIError)(nil)}, AuthInfo:protonmail.AuthInfo{version:0, modulus:"", serverEphemeral:"", salt:"", srpSession:""}, Version:4, Modulus:"<pgp signed message with signature>", ServerEphemeral:"<base64 data>", Salt:"<salt>", SRPSession:"<data>"}
3 NO cannot re-authenticate: two factor authentication enabled, please login manually
```
I wasn't sure what info in this log is sensitive, so I redacted everything that looked like some kind of hash or encoded data. Values in angle brackets `<>` (and only them) are redacted by me.

**Comment by emersion** [comment]
The refresh token is probably expired. Can you try to authenticate again? (`hydroxide auth <username>`)

**Comment by eternal-sorrow** [comment]
Okay, after reauthenticating it works.
