### ISSUE TITLE
IMAP breaks when client logs out

### ISSUE THREAD

**Issue by dvalter** [emersion/hydroxide#82]
After the last client has send `logout` to IMAP server, new connections get `database not open` on any `select`.

### Steps to reproduce:
1. Log in (IMAP)
2. Log out (IMAP)
3. Log in (IMAP)
4. Select something

Alternatively Thunderbird does that after a few hours of sleep/hibernation

Presumably caused by 83311a0

**Comment by emersion** [comment]
Are you logging in with your full e-mail address, or just your username?

**Comment by dvalter** [comment]
I use full e-mail address

**Comment by emersion** [comment]
Okay. Then there's a good chance 5cd1c7a9211f7d24e9fa57bce39a41e65dd2adb7 will fix your issues.

**Comment by dvalter** [comment]
I can't reproduce it with the latest master commits, so I think it's fixed.

Thank you.
