### ISSUE TITLE
Error: cannot create messages outside the Drafts mailbox

### ISSUE THREAD

**Issue by exander77** [emersion/hydroxide#91]
What this error message means?

**Comment by emersion** [comment]
ProtonMail's API only allows to create messages in the Drafts folder. For other folders, a different endpoint is needed.

Closing as a duplicate of https://github.com/emersion/hydroxide/issues/30

**Comment by exander77** [comment]
@emersion Can you be a little more explanatory? What endpoint do you mean? They are using different API for Bridge?

**Comment by emersion** [comment]
Creating a message outside of the drafts folder requires using the `/import` API endpoint.
